// Code generated by go-swagger; DO NOT EDIT.

package network_element

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// EndExportNetworkElementReader is a Reader for the EndExportNetworkElement structure.
type EndExportNetworkElementReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EndExportNetworkElementReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEndExportNetworkElementOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewEndExportNetworkElementDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEndExportNetworkElementOK creates a EndExportNetworkElementOK with default headers values
func NewEndExportNetworkElementOK() *EndExportNetworkElementOK {
	return &EndExportNetworkElementOK{}
}

/*EndExportNetworkElementOK handles this case with default header values.

Exports of NetworkElement completed
*/
type EndExportNetworkElementOK struct {
}

func (o *EndExportNetworkElementOK) Error() string {
	return fmt.Sprintf("[POST /Exports/endExportNetworkElement][%d] endExportNetworkElementOK ", 200)
}

func (o *EndExportNetworkElementOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEndExportNetworkElementDefault creates a EndExportNetworkElementDefault with default headers values
func NewEndExportNetworkElementDefault(code int) *EndExportNetworkElementDefault {
	return &EndExportNetworkElementDefault{
		_statusCode: code,
	}
}

/*EndExportNetworkElementDefault handles this case with default header values.

Error response
*/
type EndExportNetworkElementDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the end export network element default response
func (o *EndExportNetworkElementDefault) Code() int {
	return o._statusCode
}

func (o *EndExportNetworkElementDefault) Error() string {
	return fmt.Sprintf("[POST /Exports/endExportNetworkElement][%d] endExportNetworkElement default  %+v", o._statusCode, o.Payload)
}

func (o *EndExportNetworkElementDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*EndExportNetworkElementBody end export network element body
swagger:model EndExportNetworkElementBody
*/
type EndExportNetworkElementBody struct {

	// context
	Context *models.WSContext `json:"context,omitempty"`
}

// Validate validates this end export network element body
func (o *EndExportNetworkElementBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateContext(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *EndExportNetworkElementBody) validateContext(formats strfmt.Registry) error {

	if swag.IsZero(o.Context) { // not required
		return nil
	}

	if o.Context != nil {
		if err := o.Context.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("wscontext" + "." + "context")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *EndExportNetworkElementBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *EndExportNetworkElementBody) UnmarshalBinary(b []byte) error {
	var res EndExportNetworkElementBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
