// Code generated by go-swagger; DO NOT EDIT.

package network_element

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// InitExportNetworkElementReader is a Reader for the InitExportNetworkElement structure.
type InitExportNetworkElementReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InitExportNetworkElementReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewInitExportNetworkElementOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewInitExportNetworkElementDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewInitExportNetworkElementOK creates a InitExportNetworkElementOK with default headers values
func NewInitExportNetworkElementOK() *InitExportNetworkElementOK {
	return &InitExportNetworkElementOK{}
}

/*InitExportNetworkElementOK handles this case with default header values.

Exports of NetworkElement initialized
*/
type InitExportNetworkElementOK struct {
	Payload *models.WSContext
}

func (o *InitExportNetworkElementOK) Error() string {
	return fmt.Sprintf("[POST /Exports/initExportNetworkElement][%d] initExportNetworkElementOK  %+v", 200, o.Payload)
}

func (o *InitExportNetworkElementOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WSContext)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewInitExportNetworkElementDefault creates a InitExportNetworkElementDefault with default headers values
func NewInitExportNetworkElementDefault(code int) *InitExportNetworkElementDefault {
	return &InitExportNetworkElementDefault{
		_statusCode: code,
	}
}

/*InitExportNetworkElementDefault handles this case with default header values.

Error response
*/
type InitExportNetworkElementDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the init export network element default response
func (o *InitExportNetworkElementDefault) Code() int {
	return o._statusCode
}

func (o *InitExportNetworkElementDefault) Error() string {
	return fmt.Sprintf("[POST /Exports/initExportNetworkElement][%d] initExportNetworkElement default  %+v", o._statusCode, o.Payload)
}

func (o *InitExportNetworkElementDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*InitExportNetworkElementBody init export network element body
swagger:model InitExportNetworkElementBody
*/
type InitExportNetworkElementBody struct {

	// filter
	Filter string `json:"filter,omitempty"`

	// first result pos
	FirstResultPos int64 `json:"firstResultPos,omitempty"`

	// options
	Options []string `json:"options"`

	// page size
	PageSize int64 `json:"pageSize,omitempty"`
}

// Validate validates this init export network element body
func (o *InitExportNetworkElementBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *InitExportNetworkElementBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *InitExportNetworkElementBody) UnmarshalBinary(b []byte) error {
	var res InitExportNetworkElementBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
