// Code generated by go-swagger; DO NOT EDIT.

package tag_association

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewEndExportTagAssociationParams creates a new EndExportTagAssociationParams object
// with the default values initialized.
func NewEndExportTagAssociationParams() *EndExportTagAssociationParams {
	var ()
	return &EndExportTagAssociationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEndExportTagAssociationParamsWithTimeout creates a new EndExportTagAssociationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEndExportTagAssociationParamsWithTimeout(timeout time.Duration) *EndExportTagAssociationParams {
	var ()
	return &EndExportTagAssociationParams{

		timeout: timeout,
	}
}

// NewEndExportTagAssociationParamsWithContext creates a new EndExportTagAssociationParams object
// with the default values initialized, and the ability to set a context for a request
func NewEndExportTagAssociationParamsWithContext(ctx context.Context) *EndExportTagAssociationParams {
	var ()
	return &EndExportTagAssociationParams{

		Context: ctx,
	}
}

// NewEndExportTagAssociationParamsWithHTTPClient creates a new EndExportTagAssociationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEndExportTagAssociationParamsWithHTTPClient(client *http.Client) *EndExportTagAssociationParams {
	var ()
	return &EndExportTagAssociationParams{
		HTTPClient: client,
	}
}

/*EndExportTagAssociationParams contains all the parameters to send to the API endpoint
for the end export tag association operation typically these are written to a http.Request
*/
type EndExportTagAssociationParams struct {

	/*Wscontext
	  The results from the operation

	*/
	Wscontext EndExportTagAssociationBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the end export tag association params
func (o *EndExportTagAssociationParams) WithTimeout(timeout time.Duration) *EndExportTagAssociationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the end export tag association params
func (o *EndExportTagAssociationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the end export tag association params
func (o *EndExportTagAssociationParams) WithContext(ctx context.Context) *EndExportTagAssociationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the end export tag association params
func (o *EndExportTagAssociationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the end export tag association params
func (o *EndExportTagAssociationParams) WithHTTPClient(client *http.Client) *EndExportTagAssociationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the end export tag association params
func (o *EndExportTagAssociationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWscontext adds the wscontext to the end export tag association params
func (o *EndExportTagAssociationParams) WithWscontext(wscontext EndExportTagAssociationBody) *EndExportTagAssociationParams {
	o.SetWscontext(wscontext)
	return o
}

// SetWscontext adds the wscontext to the end export tag association params
func (o *EndExportTagAssociationParams) SetWscontext(wscontext EndExportTagAssociationBody) {
	o.Wscontext = wscontext
}

// WriteToRequest writes these params to a swagger request
func (o *EndExportTagAssociationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Wscontext); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
