// Code generated by go-swagger; DO NOT EDIT.

package address_pool

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// EndExportAddressPoolReader is a Reader for the EndExportAddressPool structure.
type EndExportAddressPoolReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EndExportAddressPoolReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEndExportAddressPoolOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewEndExportAddressPoolDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEndExportAddressPoolOK creates a EndExportAddressPoolOK with default headers values
func NewEndExportAddressPoolOK() *EndExportAddressPoolOK {
	return &EndExportAddressPoolOK{}
}

/*EndExportAddressPoolOK handles this case with default header values.

Exports of AddressPool completed
*/
type EndExportAddressPoolOK struct {
}

func (o *EndExportAddressPoolOK) Error() string {
	return fmt.Sprintf("[POST /Exports/endExportAddressPool][%d] endExportAddressPoolOK ", 200)
}

func (o *EndExportAddressPoolOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEndExportAddressPoolDefault creates a EndExportAddressPoolDefault with default headers values
func NewEndExportAddressPoolDefault(code int) *EndExportAddressPoolDefault {
	return &EndExportAddressPoolDefault{
		_statusCode: code,
	}
}

/*EndExportAddressPoolDefault handles this case with default header values.

Error response
*/
type EndExportAddressPoolDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the end export address pool default response
func (o *EndExportAddressPoolDefault) Code() int {
	return o._statusCode
}

func (o *EndExportAddressPoolDefault) Error() string {
	return fmt.Sprintf("[POST /Exports/endExportAddressPool][%d] endExportAddressPool default  %+v", o._statusCode, o.Payload)
}

func (o *EndExportAddressPoolDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*EndExportAddressPoolBody end export address pool body
swagger:model EndExportAddressPoolBody
*/
type EndExportAddressPoolBody struct {

	// context
	Context *models.WSContext `json:"context,omitempty"`
}

// Validate validates this end export address pool body
func (o *EndExportAddressPoolBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateContext(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *EndExportAddressPoolBody) validateContext(formats strfmt.Registry) error {

	if swag.IsZero(o.Context) { // not required
		return nil
	}

	if o.Context != nil {
		if err := o.Context.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("wscontext" + "." + "context")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *EndExportAddressPoolBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *EndExportAddressPoolBody) UnmarshalBinary(b []byte) error {
	var res EndExportAddressPoolBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
