// Code generated by go-swagger; DO NOT EDIT.

package address_pool

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAddressPoolParams creates a new GetAddressPoolParams object
// with the default values initialized.
func NewGetAddressPoolParams() *GetAddressPoolParams {
	var ()
	return &GetAddressPoolParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAddressPoolParamsWithTimeout creates a new GetAddressPoolParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAddressPoolParamsWithTimeout(timeout time.Duration) *GetAddressPoolParams {
	var ()
	return &GetAddressPoolParams{

		timeout: timeout,
	}
}

// NewGetAddressPoolParamsWithContext creates a new GetAddressPoolParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAddressPoolParamsWithContext(ctx context.Context) *GetAddressPoolParams {
	var ()
	return &GetAddressPoolParams{

		Context: ctx,
	}
}

// NewGetAddressPoolParamsWithHTTPClient creates a new GetAddressPoolParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAddressPoolParamsWithHTTPClient(client *http.Client) *GetAddressPoolParams {
	var ()
	return &GetAddressPoolParams{
		HTTPClient: client,
	}
}

/*GetAddressPoolParams contains all the parameters to send to the API endpoint
for the get address pool operation typically these are written to a http.Request
*/
type GetAddressPoolParams struct {

	/*Container
	  The container holding the block. Required only if start address is not unique.

	*/
	Container *string
	/*StartAddress
	  The starting address of the address pool, e.g. 10.0.0.0

	*/
	StartAddress string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get address pool params
func (o *GetAddressPoolParams) WithTimeout(timeout time.Duration) *GetAddressPoolParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get address pool params
func (o *GetAddressPoolParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get address pool params
func (o *GetAddressPoolParams) WithContext(ctx context.Context) *GetAddressPoolParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get address pool params
func (o *GetAddressPoolParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get address pool params
func (o *GetAddressPoolParams) WithHTTPClient(client *http.Client) *GetAddressPoolParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get address pool params
func (o *GetAddressPoolParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContainer adds the container to the get address pool params
func (o *GetAddressPoolParams) WithContainer(container *string) *GetAddressPoolParams {
	o.SetContainer(container)
	return o
}

// SetContainer adds the container to the get address pool params
func (o *GetAddressPoolParams) SetContainer(container *string) {
	o.Container = container
}

// WithStartAddress adds the startAddress to the get address pool params
func (o *GetAddressPoolParams) WithStartAddress(startAddress string) *GetAddressPoolParams {
	o.SetStartAddress(startAddress)
	return o
}

// SetStartAddress adds the startAddress to the get address pool params
func (o *GetAddressPoolParams) SetStartAddress(startAddress string) {
	o.StartAddress = startAddress
}

// WriteToRequest writes these params to a swagger request
func (o *GetAddressPoolParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Container != nil {

		// query param container
		var qrContainer string
		if o.Container != nil {
			qrContainer = *o.Container
		}
		qContainer := qrContainer
		if qContainer != "" {
			if err := r.SetQueryParam("container", qContainer); err != nil {
				return err
			}
		}

	}

	// query param startAddress
	qrStartAddress := o.StartAddress
	qStartAddress := qrStartAddress
	if qStartAddress != "" {
		if err := r.SetQueryParam("startAddress", qStartAddress); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
