// Code generated by go-swagger; DO NOT EDIT.

package d_h_c_p_option_set

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewEndExportDhcpOptionSetParams creates a new EndExportDhcpOptionSetParams object
// with the default values initialized.
func NewEndExportDhcpOptionSetParams() *EndExportDhcpOptionSetParams {
	var ()
	return &EndExportDhcpOptionSetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEndExportDhcpOptionSetParamsWithTimeout creates a new EndExportDhcpOptionSetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEndExportDhcpOptionSetParamsWithTimeout(timeout time.Duration) *EndExportDhcpOptionSetParams {
	var ()
	return &EndExportDhcpOptionSetParams{

		timeout: timeout,
	}
}

// NewEndExportDhcpOptionSetParamsWithContext creates a new EndExportDhcpOptionSetParams object
// with the default values initialized, and the ability to set a context for a request
func NewEndExportDhcpOptionSetParamsWithContext(ctx context.Context) *EndExportDhcpOptionSetParams {
	var ()
	return &EndExportDhcpOptionSetParams{

		Context: ctx,
	}
}

// NewEndExportDhcpOptionSetParamsWithHTTPClient creates a new EndExportDhcpOptionSetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEndExportDhcpOptionSetParamsWithHTTPClient(client *http.Client) *EndExportDhcpOptionSetParams {
	var ()
	return &EndExportDhcpOptionSetParams{
		HTTPClient: client,
	}
}

/*EndExportDhcpOptionSetParams contains all the parameters to send to the API endpoint
for the end export dhcp option set operation typically these are written to a http.Request
*/
type EndExportDhcpOptionSetParams struct {

	/*Wscontext
	  The results from an exportDhcpOptionSet operation

	*/
	Wscontext EndExportDhcpOptionSetBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the end export dhcp option set params
func (o *EndExportDhcpOptionSetParams) WithTimeout(timeout time.Duration) *EndExportDhcpOptionSetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the end export dhcp option set params
func (o *EndExportDhcpOptionSetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the end export dhcp option set params
func (o *EndExportDhcpOptionSetParams) WithContext(ctx context.Context) *EndExportDhcpOptionSetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the end export dhcp option set params
func (o *EndExportDhcpOptionSetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the end export dhcp option set params
func (o *EndExportDhcpOptionSetParams) WithHTTPClient(client *http.Client) *EndExportDhcpOptionSetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the end export dhcp option set params
func (o *EndExportDhcpOptionSetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWscontext adds the wscontext to the end export dhcp option set params
func (o *EndExportDhcpOptionSetParams) WithWscontext(wscontext EndExportDhcpOptionSetBody) *EndExportDhcpOptionSetParams {
	o.SetWscontext(wscontext)
	return o
}

// SetWscontext adds the wscontext to the end export dhcp option set params
func (o *EndExportDhcpOptionSetParams) SetWscontext(wscontext EndExportDhcpOptionSetBody) {
	o.Wscontext = wscontext
}

// WriteToRequest writes these params to a swagger request
func (o *EndExportDhcpOptionSetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Wscontext); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
