// Code generated by go-swagger; DO NOT EDIT.

package d_h_c_p_option_set

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// EndExportDhcpOptionSetReader is a Reader for the EndExportDhcpOptionSet structure.
type EndExportDhcpOptionSetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EndExportDhcpOptionSetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEndExportDhcpOptionSetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewEndExportDhcpOptionSetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEndExportDhcpOptionSetOK creates a EndExportDhcpOptionSetOK with default headers values
func NewEndExportDhcpOptionSetOK() *EndExportDhcpOptionSetOK {
	return &EndExportDhcpOptionSetOK{}
}

/*EndExportDhcpOptionSetOK handles this case with default header values.

Exports of DhcpOptionSet completed
*/
type EndExportDhcpOptionSetOK struct {
}

func (o *EndExportDhcpOptionSetOK) Error() string {
	return fmt.Sprintf("[POST /Exports/endExportDhcpOptionSet][%d] endExportDhcpOptionSetOK ", 200)
}

func (o *EndExportDhcpOptionSetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEndExportDhcpOptionSetDefault creates a EndExportDhcpOptionSetDefault with default headers values
func NewEndExportDhcpOptionSetDefault(code int) *EndExportDhcpOptionSetDefault {
	return &EndExportDhcpOptionSetDefault{
		_statusCode: code,
	}
}

/*EndExportDhcpOptionSetDefault handles this case with default header values.

Error response
*/
type EndExportDhcpOptionSetDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the end export dhcp option set default response
func (o *EndExportDhcpOptionSetDefault) Code() int {
	return o._statusCode
}

func (o *EndExportDhcpOptionSetDefault) Error() string {
	return fmt.Sprintf("[POST /Exports/endExportDhcpOptionSet][%d] endExportDhcpOptionSet default  %+v", o._statusCode, o.Payload)
}

func (o *EndExportDhcpOptionSetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*EndExportDhcpOptionSetBody end export dhcp option set body
swagger:model EndExportDhcpOptionSetBody
*/
type EndExportDhcpOptionSetBody struct {

	// context
	Context *models.WSContext `json:"context,omitempty"`
}

// Validate validates this end export dhcp option set body
func (o *EndExportDhcpOptionSetBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateContext(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *EndExportDhcpOptionSetBody) validateContext(formats strfmt.Registry) error {

	if swag.IsZero(o.Context) { // not required
		return nil
	}

	if o.Context != nil {
		if err := o.Context.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("wscontext" + "." + "context")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *EndExportDhcpOptionSetBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *EndExportDhcpOptionSetBody) UnmarshalBinary(b []byte) error {
	var res EndExportDhcpOptionSetBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
