// Code generated by go-swagger; DO NOT EDIT.

package d_h_c_p_option_set

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewImportDhcpOptionSetParams creates a new ImportDhcpOptionSetParams object
// with the default values initialized.
func NewImportDhcpOptionSetParams() *ImportDhcpOptionSetParams {
	var ()
	return &ImportDhcpOptionSetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewImportDhcpOptionSetParamsWithTimeout creates a new ImportDhcpOptionSetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewImportDhcpOptionSetParamsWithTimeout(timeout time.Duration) *ImportDhcpOptionSetParams {
	var ()
	return &ImportDhcpOptionSetParams{

		timeout: timeout,
	}
}

// NewImportDhcpOptionSetParamsWithContext creates a new ImportDhcpOptionSetParams object
// with the default values initialized, and the ability to set a context for a request
func NewImportDhcpOptionSetParamsWithContext(ctx context.Context) *ImportDhcpOptionSetParams {
	var ()
	return &ImportDhcpOptionSetParams{

		Context: ctx,
	}
}

// NewImportDhcpOptionSetParamsWithHTTPClient creates a new ImportDhcpOptionSetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewImportDhcpOptionSetParamsWithHTTPClient(client *http.Client) *ImportDhcpOptionSetParams {
	var ()
	return &ImportDhcpOptionSetParams{
		HTTPClient: client,
	}
}

/*ImportDhcpOptionSetParams contains all the parameters to send to the API endpoint
for the import dhcp option set operation typically these are written to a http.Request
*/
type ImportDhcpOptionSetParams struct {

	/*ImportParameters
	  The input describing the DHCP option set.  Required parameters are: name, scopeName and scopeType for scope-specific sets only, code or name and optionValue for each option.

	*/
	ImportParameters ImportDhcpOptionSetBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the import dhcp option set params
func (o *ImportDhcpOptionSetParams) WithTimeout(timeout time.Duration) *ImportDhcpOptionSetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the import dhcp option set params
func (o *ImportDhcpOptionSetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the import dhcp option set params
func (o *ImportDhcpOptionSetParams) WithContext(ctx context.Context) *ImportDhcpOptionSetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the import dhcp option set params
func (o *ImportDhcpOptionSetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the import dhcp option set params
func (o *ImportDhcpOptionSetParams) WithHTTPClient(client *http.Client) *ImportDhcpOptionSetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the import dhcp option set params
func (o *ImportDhcpOptionSetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithImportParameters adds the importParameters to the import dhcp option set params
func (o *ImportDhcpOptionSetParams) WithImportParameters(importParameters ImportDhcpOptionSetBody) *ImportDhcpOptionSetParams {
	o.SetImportParameters(importParameters)
	return o
}

// SetImportParameters adds the importParameters to the import dhcp option set params
func (o *ImportDhcpOptionSetParams) SetImportParameters(importParameters ImportDhcpOptionSetBody) {
	o.ImportParameters = importParameters
}

// WriteToRequest writes these params to a swagger request
func (o *ImportDhcpOptionSetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.ImportParameters); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
