// Code generated by go-swagger; DO NOT EDIT.

package resource_record

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewEndExportZoneResourceRecParams creates a new EndExportZoneResourceRecParams object
// with the default values initialized.
func NewEndExportZoneResourceRecParams() *EndExportZoneResourceRecParams {
	var ()
	return &EndExportZoneResourceRecParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEndExportZoneResourceRecParamsWithTimeout creates a new EndExportZoneResourceRecParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEndExportZoneResourceRecParamsWithTimeout(timeout time.Duration) *EndExportZoneResourceRecParams {
	var ()
	return &EndExportZoneResourceRecParams{

		timeout: timeout,
	}
}

// NewEndExportZoneResourceRecParamsWithContext creates a new EndExportZoneResourceRecParams object
// with the default values initialized, and the ability to set a context for a request
func NewEndExportZoneResourceRecParamsWithContext(ctx context.Context) *EndExportZoneResourceRecParams {
	var ()
	return &EndExportZoneResourceRecParams{

		Context: ctx,
	}
}

// NewEndExportZoneResourceRecParamsWithHTTPClient creates a new EndExportZoneResourceRecParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEndExportZoneResourceRecParamsWithHTTPClient(client *http.Client) *EndExportZoneResourceRecParams {
	var ()
	return &EndExportZoneResourceRecParams{
		HTTPClient: client,
	}
}

/*EndExportZoneResourceRecParams contains all the parameters to send to the API endpoint
for the end export zone resource rec operation typically these are written to a http.Request
*/
type EndExportZoneResourceRecParams struct {

	/*Wscontext
	  The results from an exportZoneResourceRec operation

	*/
	Wscontext EndExportZoneResourceRecBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the end export zone resource rec params
func (o *EndExportZoneResourceRecParams) WithTimeout(timeout time.Duration) *EndExportZoneResourceRecParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the end export zone resource rec params
func (o *EndExportZoneResourceRecParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the end export zone resource rec params
func (o *EndExportZoneResourceRecParams) WithContext(ctx context.Context) *EndExportZoneResourceRecParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the end export zone resource rec params
func (o *EndExportZoneResourceRecParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the end export zone resource rec params
func (o *EndExportZoneResourceRecParams) WithHTTPClient(client *http.Client) *EndExportZoneResourceRecParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the end export zone resource rec params
func (o *EndExportZoneResourceRecParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWscontext adds the wscontext to the end export zone resource rec params
func (o *EndExportZoneResourceRecParams) WithWscontext(wscontext EndExportZoneResourceRecBody) *EndExportZoneResourceRecParams {
	o.SetWscontext(wscontext)
	return o
}

// SetWscontext adds the wscontext to the end export zone resource rec params
func (o *EndExportZoneResourceRecParams) SetWscontext(wscontext EndExportZoneResourceRecBody) {
	o.Wscontext = wscontext
}

// WriteToRequest writes these params to a swagger request
func (o *EndExportZoneResourceRecParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Wscontext); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
