// Code generated by go-swagger; DO NOT EDIT.

package resource_record

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// EndExportResourceRecordRestoreListReader is a Reader for the EndExportResourceRecordRestoreList structure.
type EndExportResourceRecordRestoreListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EndExportResourceRecordRestoreListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEndExportResourceRecordRestoreListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewEndExportResourceRecordRestoreListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEndExportResourceRecordRestoreListOK creates a EndExportResourceRecordRestoreListOK with default headers values
func NewEndExportResourceRecordRestoreListOK() *EndExportResourceRecordRestoreListOK {
	return &EndExportResourceRecordRestoreListOK{}
}

/*EndExportResourceRecordRestoreListOK handles this case with default header values.

Exports of ResourceRecordRestoreList completed
*/
type EndExportResourceRecordRestoreListOK struct {
}

func (o *EndExportResourceRecordRestoreListOK) Error() string {
	return fmt.Sprintf("[POST /Exports/endExportResourceRecordRestoreList][%d] endExportResourceRecordRestoreListOK ", 200)
}

func (o *EndExportResourceRecordRestoreListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEndExportResourceRecordRestoreListDefault creates a EndExportResourceRecordRestoreListDefault with default headers values
func NewEndExportResourceRecordRestoreListDefault(code int) *EndExportResourceRecordRestoreListDefault {
	return &EndExportResourceRecordRestoreListDefault{
		_statusCode: code,
	}
}

/*EndExportResourceRecordRestoreListDefault handles this case with default header values.

Error response
*/
type EndExportResourceRecordRestoreListDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the end export resource record restore list default response
func (o *EndExportResourceRecordRestoreListDefault) Code() int {
	return o._statusCode
}

func (o *EndExportResourceRecordRestoreListDefault) Error() string {
	return fmt.Sprintf("[POST /Exports/endExportResourceRecordRestoreList][%d] endExportResourceRecordRestoreList default  %+v", o._statusCode, o.Payload)
}

func (o *EndExportResourceRecordRestoreListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*EndExportResourceRecordRestoreListBody end export resource record restore list body
swagger:model EndExportResourceRecordRestoreListBody
*/
type EndExportResourceRecordRestoreListBody struct {

	// context
	Context *models.WSContext `json:"context,omitempty"`
}

// Validate validates this end export resource record restore list body
func (o *EndExportResourceRecordRestoreListBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateContext(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *EndExportResourceRecordRestoreListBody) validateContext(formats strfmt.Registry) error {

	if swag.IsZero(o.Context) { // not required
		return nil
	}

	if o.Context != nil {
		if err := o.Context.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("wscontext" + "." + "context")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *EndExportResourceRecordRestoreListBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *EndExportResourceRecordRestoreListBody) UnmarshalBinary(b []byte) error {
	var res EndExportResourceRecordRestoreListBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
