// Code generated by go-swagger; DO NOT EDIT.

package resource_record

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// EndExportDomainResourceRecReader is a Reader for the EndExportDomainResourceRec structure.
type EndExportDomainResourceRecReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EndExportDomainResourceRecReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEndExportDomainResourceRecOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewEndExportDomainResourceRecDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEndExportDomainResourceRecOK creates a EndExportDomainResourceRecOK with default headers values
func NewEndExportDomainResourceRecOK() *EndExportDomainResourceRecOK {
	return &EndExportDomainResourceRecOK{}
}

/*EndExportDomainResourceRecOK handles this case with default header values.

Exports of DomainResourceRec completed
*/
type EndExportDomainResourceRecOK struct {
}

func (o *EndExportDomainResourceRecOK) Error() string {
	return fmt.Sprintf("[POST /Exports/endExportDomainResourceRec][%d] endExportDomainResourceRecOK ", 200)
}

func (o *EndExportDomainResourceRecOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEndExportDomainResourceRecDefault creates a EndExportDomainResourceRecDefault with default headers values
func NewEndExportDomainResourceRecDefault(code int) *EndExportDomainResourceRecDefault {
	return &EndExportDomainResourceRecDefault{
		_statusCode: code,
	}
}

/*EndExportDomainResourceRecDefault handles this case with default header values.

Error response
*/
type EndExportDomainResourceRecDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the end export domain resource rec default response
func (o *EndExportDomainResourceRecDefault) Code() int {
	return o._statusCode
}

func (o *EndExportDomainResourceRecDefault) Error() string {
	return fmt.Sprintf("[POST /Exports/endExportDomainResourceRec][%d] endExportDomainResourceRec default  %+v", o._statusCode, o.Payload)
}

func (o *EndExportDomainResourceRecDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*EndExportDomainResourceRecBody end export domain resource rec body
swagger:model EndExportDomainResourceRecBody
*/
type EndExportDomainResourceRecBody struct {

	// context
	Context *models.WSContext `json:"context,omitempty"`
}

// Validate validates this end export domain resource rec body
func (o *EndExportDomainResourceRecBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateContext(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *EndExportDomainResourceRecBody) validateContext(formats strfmt.Registry) error {

	if swag.IsZero(o.Context) { // not required
		return nil
	}

	if o.Context != nil {
		if err := o.Context.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("wscontext" + "." + "context")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *EndExportDomainResourceRecBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *EndExportDomainResourceRecBody) UnmarshalBinary(b []byte) error {
	var res EndExportDomainResourceRecBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
