// Code generated by go-swagger; DO NOT EDIT.

package resource_record

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// ExportDeviceResourceRecReader is a Reader for the ExportDeviceResourceRec structure.
type ExportDeviceResourceRecReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExportDeviceResourceRecReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewExportDeviceResourceRecOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewExportDeviceResourceRecDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewExportDeviceResourceRecOK creates a ExportDeviceResourceRecOK with default headers values
func NewExportDeviceResourceRecOK() *ExportDeviceResourceRecOK {
	return &ExportDeviceResourceRecOK{}
}

/*ExportDeviceResourceRecOK handles this case with default header values.

DeviceResourceRec returned
*/
type ExportDeviceResourceRecOK struct {
	Payload []*models.WSDeviceResourceRec
}

func (o *ExportDeviceResourceRecOK) Error() string {
	return fmt.Sprintf("[POST /Exports/exportDeviceResourceRec][%d] exportDeviceResourceRecOK  %+v", 200, o.Payload)
}

func (o *ExportDeviceResourceRecOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExportDeviceResourceRecDefault creates a ExportDeviceResourceRecDefault with default headers values
func NewExportDeviceResourceRecDefault(code int) *ExportDeviceResourceRecDefault {
	return &ExportDeviceResourceRecDefault{
		_statusCode: code,
	}
}

/*ExportDeviceResourceRecDefault handles this case with default header values.

Error response
*/
type ExportDeviceResourceRecDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the export device resource rec default response
func (o *ExportDeviceResourceRecDefault) Code() int {
	return o._statusCode
}

func (o *ExportDeviceResourceRecDefault) Error() string {
	return fmt.Sprintf("[POST /Exports/exportDeviceResourceRec][%d] exportDeviceResourceRec default  %+v", o._statusCode, o.Payload)
}

func (o *ExportDeviceResourceRecDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ExportDeviceResourceRecBody export device resource rec body
swagger:model ExportDeviceResourceRecBody
*/
type ExportDeviceResourceRecBody struct {

	// context
	Context *models.WSContext `json:"context,omitempty"`
}

// Validate validates this export device resource rec body
func (o *ExportDeviceResourceRecBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateContext(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ExportDeviceResourceRecBody) validateContext(formats strfmt.Registry) error {

	if swag.IsZero(o.Context) { // not required
		return nil
	}

	if o.Context != nil {
		if err := o.Context.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("wscontext" + "." + "context")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ExportDeviceResourceRecBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ExportDeviceResourceRecBody) UnmarshalBinary(b []byte) error {
	var res ExportDeviceResourceRecBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
