// Code generated by go-swagger; DO NOT EDIT.

package resource_record

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// GetDomainResourceRecReader is a Reader for the GetDomainResourceRec structure.
type GetDomainResourceRecReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDomainResourceRecReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDomainResourceRecOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetDomainResourceRecDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetDomainResourceRecOK creates a GetDomainResourceRecOK with default headers values
func NewGetDomainResourceRecOK() *GetDomainResourceRecOK {
	return &GetDomainResourceRecOK{}
}

/*GetDomainResourceRecOK handles this case with default header values.

DomainResourceRec
*/
type GetDomainResourceRecOK struct {
	Payload *models.WSDomainResourceRec
}

func (o *GetDomainResourceRecOK) Error() string {
	return fmt.Sprintf("[GET /Gets/getDomainResourceRec][%d] getDomainResourceRecOK  %+v", 200, o.Payload)
}

func (o *GetDomainResourceRecOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WSDomainResourceRec)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDomainResourceRecDefault creates a GetDomainResourceRecDefault with default headers values
func NewGetDomainResourceRecDefault(code int) *GetDomainResourceRecDefault {
	return &GetDomainResourceRecDefault{
		_statusCode: code,
	}
}

/*GetDomainResourceRecDefault handles this case with default header values.

Error response
*/
type GetDomainResourceRecDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the get domain resource rec default response
func (o *GetDomainResourceRecDefault) Code() int {
	return o._statusCode
}

func (o *GetDomainResourceRecDefault) Error() string {
	return fmt.Sprintf("[GET /Gets/getDomainResourceRec][%d] getDomainResourceRec default  %+v", o._statusCode, o.Payload)
}

func (o *GetDomainResourceRecDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
