// Code generated by go-swagger; DO NOT EDIT.

package resource_record

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// ImportDomainResourceRecordReader is a Reader for the ImportDomainResourceRecord structure.
type ImportDomainResourceRecordReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ImportDomainResourceRecordReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewImportDomainResourceRecordOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewImportDomainResourceRecordDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewImportDomainResourceRecordOK creates a ImportDomainResourceRecordOK with default headers values
func NewImportDomainResourceRecordOK() *ImportDomainResourceRecordOK {
	return &ImportDomainResourceRecordOK{}
}

/*ImportDomainResourceRecordOK handles this case with default header values.

Imports of DomainResourceRecord completed
*/
type ImportDomainResourceRecordOK struct {
}

func (o *ImportDomainResourceRecordOK) Error() string {
	return fmt.Sprintf("[POST /Imports/importDomainResourceRecord][%d] importDomainResourceRecordOK ", 200)
}

func (o *ImportDomainResourceRecordOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewImportDomainResourceRecordDefault creates a ImportDomainResourceRecordDefault with default headers values
func NewImportDomainResourceRecordDefault(code int) *ImportDomainResourceRecordDefault {
	return &ImportDomainResourceRecordDefault{
		_statusCode: code,
	}
}

/*ImportDomainResourceRecordDefault handles this case with default header values.

Error response
*/
type ImportDomainResourceRecordDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the import domain resource record default response
func (o *ImportDomainResourceRecordDefault) Code() int {
	return o._statusCode
}

func (o *ImportDomainResourceRecordDefault) Error() string {
	return fmt.Sprintf("[POST /Imports/importDomainResourceRecord][%d] importDomainResourceRecord default  %+v", o._statusCode, o.Payload)
}

func (o *ImportDomainResourceRecordDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ImportDomainResourceRecordBody import domain resource record body
swagger:model ImportDomainResourceRecordBody
*/
type ImportDomainResourceRecordBody struct {

	// inp r r
	InpRR *models.WSDomainResourceRec `json:"inpRR,omitempty"`
}

// Validate validates this import domain resource record body
func (o *ImportDomainResourceRecordBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateInpRR(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ImportDomainResourceRecordBody) validateInpRR(formats strfmt.Registry) error {

	if swag.IsZero(o.InpRR) { // not required
		return nil
	}

	if o.InpRR != nil {
		if err := o.InpRR.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Import Parameters" + "." + "inpRR")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ImportDomainResourceRecordBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ImportDomainResourceRecordBody) UnmarshalBinary(b []byte) error {
	var res ImportDomainResourceRecordBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
