// Code generated by go-swagger; DO NOT EDIT.

package resource_record

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewInitExportDomainResourceRecParams creates a new InitExportDomainResourceRecParams object
// with the default values initialized.
func NewInitExportDomainResourceRecParams() *InitExportDomainResourceRecParams {
	var ()
	return &InitExportDomainResourceRecParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewInitExportDomainResourceRecParamsWithTimeout creates a new InitExportDomainResourceRecParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewInitExportDomainResourceRecParamsWithTimeout(timeout time.Duration) *InitExportDomainResourceRecParams {
	var ()
	return &InitExportDomainResourceRecParams{

		timeout: timeout,
	}
}

// NewInitExportDomainResourceRecParamsWithContext creates a new InitExportDomainResourceRecParams object
// with the default values initialized, and the ability to set a context for a request
func NewInitExportDomainResourceRecParamsWithContext(ctx context.Context) *InitExportDomainResourceRecParams {
	var ()
	return &InitExportDomainResourceRecParams{

		Context: ctx,
	}
}

// NewInitExportDomainResourceRecParamsWithHTTPClient creates a new InitExportDomainResourceRecParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewInitExportDomainResourceRecParamsWithHTTPClient(client *http.Client) *InitExportDomainResourceRecParams {
	var ()
	return &InitExportDomainResourceRecParams{
		HTTPClient: client,
	}
}

/*InitExportDomainResourceRecParams contains all the parameters to send to the API endpoint
for the init export domain resource rec operation typically these are written to a http.Request
*/
type InitExportDomainResourceRecParams struct {

	/*ExportParameters
	  The query string syntax and supported selectors are defined in the IPControl CLI and API Guide. Use pageSize to specify the number of results to be returned. Use firstResultPos to indicate where the set of results should begin. Results begin at position 0. includeDeviceRRs is the only supported option for this operation.

	*/
	ExportParameters InitExportDomainResourceRecBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the init export domain resource rec params
func (o *InitExportDomainResourceRecParams) WithTimeout(timeout time.Duration) *InitExportDomainResourceRecParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the init export domain resource rec params
func (o *InitExportDomainResourceRecParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the init export domain resource rec params
func (o *InitExportDomainResourceRecParams) WithContext(ctx context.Context) *InitExportDomainResourceRecParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the init export domain resource rec params
func (o *InitExportDomainResourceRecParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the init export domain resource rec params
func (o *InitExportDomainResourceRecParams) WithHTTPClient(client *http.Client) *InitExportDomainResourceRecParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the init export domain resource rec params
func (o *InitExportDomainResourceRecParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithExportParameters adds the exportParameters to the init export domain resource rec params
func (o *InitExportDomainResourceRecParams) WithExportParameters(exportParameters InitExportDomainResourceRecBody) *InitExportDomainResourceRecParams {
	o.SetExportParameters(exportParameters)
	return o
}

// SetExportParameters adds the exportParameters to the init export domain resource rec params
func (o *InitExportDomainResourceRecParams) SetExportParameters(exportParameters InitExportDomainResourceRecBody) {
	o.ExportParameters = exportParameters
}

// WriteToRequest writes these params to a swagger request
func (o *InitExportDomainResourceRecParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.ExportParameters); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
