// Code generated by go-swagger; DO NOT EDIT.

package resource_record

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// InitExportDeviceResourceRecReader is a Reader for the InitExportDeviceResourceRec structure.
type InitExportDeviceResourceRecReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InitExportDeviceResourceRecReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewInitExportDeviceResourceRecOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewInitExportDeviceResourceRecDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewInitExportDeviceResourceRecOK creates a InitExportDeviceResourceRecOK with default headers values
func NewInitExportDeviceResourceRecOK() *InitExportDeviceResourceRecOK {
	return &InitExportDeviceResourceRecOK{}
}

/*InitExportDeviceResourceRecOK handles this case with default header values.

Exports of DeviceResourceRec initialized
*/
type InitExportDeviceResourceRecOK struct {
	Payload *models.WSContext
}

func (o *InitExportDeviceResourceRecOK) Error() string {
	return fmt.Sprintf("[POST /Exports/initExportDeviceResourceRec][%d] initExportDeviceResourceRecOK  %+v", 200, o.Payload)
}

func (o *InitExportDeviceResourceRecOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WSContext)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewInitExportDeviceResourceRecDefault creates a InitExportDeviceResourceRecDefault with default headers values
func NewInitExportDeviceResourceRecDefault(code int) *InitExportDeviceResourceRecDefault {
	return &InitExportDeviceResourceRecDefault{
		_statusCode: code,
	}
}

/*InitExportDeviceResourceRecDefault handles this case with default header values.

Error response
*/
type InitExportDeviceResourceRecDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the init export device resource rec default response
func (o *InitExportDeviceResourceRecDefault) Code() int {
	return o._statusCode
}

func (o *InitExportDeviceResourceRecDefault) Error() string {
	return fmt.Sprintf("[POST /Exports/initExportDeviceResourceRec][%d] initExportDeviceResourceRec default  %+v", o._statusCode, o.Payload)
}

func (o *InitExportDeviceResourceRecDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*InitExportDeviceResourceRecBody init export device resource rec body
swagger:model InitExportDeviceResourceRecBody
*/
type InitExportDeviceResourceRecBody struct {

	// filter
	Filter string `json:"filter,omitempty"`

	// first result pos
	FirstResultPos int64 `json:"firstResultPos,omitempty"`

	// options
	Options []string `json:"options"`

	// page size
	PageSize int64 `json:"pageSize,omitempty"`
}

// Validate validates this init export device resource rec body
func (o *InitExportDeviceResourceRecBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *InitExportDeviceResourceRecBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *InitExportDeviceResourceRecBody) UnmarshalBinary(b []byte) error {
	var res InitExportDeviceResourceRecBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
