// Code generated by go-swagger; DO NOT EDIT.

package child_block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// EndExportChildBlockReader is a Reader for the EndExportChildBlock structure.
type EndExportChildBlockReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EndExportChildBlockReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEndExportChildBlockOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewEndExportChildBlockDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEndExportChildBlockOK creates a EndExportChildBlockOK with default headers values
func NewEndExportChildBlockOK() *EndExportChildBlockOK {
	return &EndExportChildBlockOK{}
}

/*EndExportChildBlockOK handles this case with default header values.

Exports of ChildBlock completed
*/
type EndExportChildBlockOK struct {
}

func (o *EndExportChildBlockOK) Error() string {
	return fmt.Sprintf("[POST /Exports/endExportChildBlock][%d] endExportChildBlockOK ", 200)
}

func (o *EndExportChildBlockOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEndExportChildBlockDefault creates a EndExportChildBlockDefault with default headers values
func NewEndExportChildBlockDefault(code int) *EndExportChildBlockDefault {
	return &EndExportChildBlockDefault{
		_statusCode: code,
	}
}

/*EndExportChildBlockDefault handles this case with default header values.

Error response
*/
type EndExportChildBlockDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the end export child block default response
func (o *EndExportChildBlockDefault) Code() int {
	return o._statusCode
}

func (o *EndExportChildBlockDefault) Error() string {
	return fmt.Sprintf("[POST /Exports/endExportChildBlock][%d] endExportChildBlock default  %+v", o._statusCode, o.Payload)
}

func (o *EndExportChildBlockDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*EndExportChildBlockBody end export child block body
swagger:model EndExportChildBlockBody
*/
type EndExportChildBlockBody struct {

	// context
	Context *models.WSContext `json:"context,omitempty"`
}

// Validate validates this end export child block body
func (o *EndExportChildBlockBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateContext(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *EndExportChildBlockBody) validateContext(formats strfmt.Registry) error {

	if swag.IsZero(o.Context) { // not required
		return nil
	}

	if o.Context != nil {
		if err := o.Context.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("wscontext" + "." + "context")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *EndExportChildBlockBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *EndExportChildBlockBody) UnmarshalBinary(b []byte) error {
	var res EndExportChildBlockBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
