// Code generated by go-swagger; DO NOT EDIT.

package child_block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// ExportChildBlockReader is a Reader for the ExportChildBlock structure.
type ExportChildBlockReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExportChildBlockReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewExportChildBlockOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewExportChildBlockDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewExportChildBlockOK creates a ExportChildBlockOK with default headers values
func NewExportChildBlockOK() *ExportChildBlockOK {
	return &ExportChildBlockOK{}
}

/*ExportChildBlockOK handles this case with default header values.

ChildBlock returned
*/
type ExportChildBlockOK struct {
	Payload []*models.WSChildSubnetBlock
}

func (o *ExportChildBlockOK) Error() string {
	return fmt.Sprintf("[POST /Exports/exportChildBlock][%d] exportChildBlockOK  %+v", 200, o.Payload)
}

func (o *ExportChildBlockOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExportChildBlockDefault creates a ExportChildBlockDefault with default headers values
func NewExportChildBlockDefault(code int) *ExportChildBlockDefault {
	return &ExportChildBlockDefault{
		_statusCode: code,
	}
}

/*ExportChildBlockDefault handles this case with default header values.

Error response
*/
type ExportChildBlockDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the export child block default response
func (o *ExportChildBlockDefault) Code() int {
	return o._statusCode
}

func (o *ExportChildBlockDefault) Error() string {
	return fmt.Sprintf("[POST /Exports/exportChildBlock][%d] exportChildBlock default  %+v", o._statusCode, o.Payload)
}

func (o *ExportChildBlockDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ExportChildBlockBody export child block body
swagger:model ExportChildBlockBody
*/
type ExportChildBlockBody struct {

	// context
	Context *models.WSContext `json:"context,omitempty"`
}

// Validate validates this export child block body
func (o *ExportChildBlockBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateContext(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ExportChildBlockBody) validateContext(formats strfmt.Registry) error {

	if swag.IsZero(o.Context) { // not required
		return nil
	}

	if o.Context != nil {
		if err := o.Context.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("wscontext" + "." + "context")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ExportChildBlockBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ExportChildBlockBody) UnmarshalBinary(b []byte) error {
	var res ExportChildBlockBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
