// Code generated by go-swagger; DO NOT EDIT.

package child_block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// ImportChildBlockReader is a Reader for the ImportChildBlock structure.
type ImportChildBlockReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ImportChildBlockReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewImportChildBlockOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewImportChildBlockDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewImportChildBlockOK creates a ImportChildBlockOK with default headers values
func NewImportChildBlockOK() *ImportChildBlockOK {
	return &ImportChildBlockOK{}
}

/*ImportChildBlockOK handles this case with default header values.

Imports of ChildBlock completed
*/
type ImportChildBlockOK struct {
	Payload *ImportChildBlockOKBody
}

func (o *ImportChildBlockOK) Error() string {
	return fmt.Sprintf("[POST /Imports/importChildBlock][%d] importChildBlockOK  %+v", 200, o.Payload)
}

func (o *ImportChildBlockOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ImportChildBlockOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewImportChildBlockDefault creates a ImportChildBlockDefault with default headers values
func NewImportChildBlockDefault(code int) *ImportChildBlockDefault {
	return &ImportChildBlockDefault{
		_statusCode: code,
	}
}

/*ImportChildBlockDefault handles this case with default header values.

Error response
*/
type ImportChildBlockDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the import child block default response
func (o *ImportChildBlockDefault) Code() int {
	return o._statusCode
}

func (o *ImportChildBlockDefault) Error() string {
	return fmt.Sprintf("[POST /Imports/importChildBlock][%d] importChildBlock default  %+v", o._statusCode, o.Payload)
}

func (o *ImportChildBlockDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ImportChildBlockBody import child block body
swagger:model ImportChildBlockBody
*/
type ImportChildBlockBody struct {

	// inp block policy
	InpBlockPolicy *models.WSSubnetPolicy `json:"inpBlockPolicy,omitempty"`

	// inp child block
	InpChildBlock *models.WSChildBlock `json:"inpChildBlock,omitempty"`
}

// Validate validates this import child block body
func (o *ImportChildBlockBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateInpBlockPolicy(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateInpChildBlock(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ImportChildBlockBody) validateInpBlockPolicy(formats strfmt.Registry) error {

	if swag.IsZero(o.InpBlockPolicy) { // not required
		return nil
	}

	if o.InpBlockPolicy != nil {
		if err := o.InpBlockPolicy.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Import Parameters, inpBlockPolicy" + "." + "inpBlockPolicy")
			}
			return err
		}
	}

	return nil
}

func (o *ImportChildBlockBody) validateInpChildBlock(formats strfmt.Registry) error {

	if swag.IsZero(o.InpChildBlock) { // not required
		return nil
	}

	if o.InpChildBlock != nil {
		if err := o.InpChildBlock.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Import Parameters, inpBlockPolicy" + "." + "inpChildBlock")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ImportChildBlockBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ImportChildBlockBody) UnmarshalBinary(b []byte) error {
	var res ImportChildBlockBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*ImportChildBlockOKBody import child block o k body
swagger:model ImportChildBlockOKBody
*/
type ImportChildBlockOKBody struct {

	// result
	Result string `json:"result,omitempty"`
}

// Validate validates this import child block o k body
func (o *ImportChildBlockOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ImportChildBlockOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ImportChildBlockOKBody) UnmarshalBinary(b []byte) error {
	var res ImportChildBlockOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
