// Code generated by go-swagger; DO NOT EDIT.

package child_block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"io/ioutil"
	"log"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// InitExportChildBlockReader is a Reader for the InitExportChildBlock structure.
type InitExportChildBlockReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InitExportChildBlockReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewInitExportChildBlockOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		log.Printf("Code=%d", response.Code())
		result := NewInitExportChildBlockDefault(response.Code())
		b, _ := ioutil.ReadAll(response.Body())
		log.Printf("%s", b)
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewInitExportChildBlockOK creates a InitExportChildBlockOK with default headers values
func NewInitExportChildBlockOK() *InitExportChildBlockOK {
	return &InitExportChildBlockOK{}
}

/*InitExportChildBlockOK handles this case with default header values.

Exports of ChildBlock initialized
*/
type InitExportChildBlockOK struct {
	Payload *models.WSContext
}

func (o *InitExportChildBlockOK) Error() string {
	return fmt.Sprintf("[POST /Exports/initExportChildBlock][%d] initExportChildBlockOK  %+v", 200, o.Payload)
}

func (o *InitExportChildBlockOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WSContext)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewInitExportChildBlockDefault creates a InitExportChildBlockDefault with default headers values
func NewInitExportChildBlockDefault(code int) *InitExportChildBlockDefault {
	return &InitExportChildBlockDefault{
		_statusCode: code,
	}
}

/*InitExportChildBlockDefault handles this case with default header values.

Error response
*/
type InitExportChildBlockDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the init export child block default response
func (o *InitExportChildBlockDefault) Code() int {
	return o._statusCode
}

func (o *InitExportChildBlockDefault) Error() string {
	return fmt.Sprintf("[POST /Exports/initExportChildBlock][%d] initExportChildBlock default  %+v", o._statusCode, o.Payload)
}

func (o *InitExportChildBlockDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*InitExportChildBlockBody init export child block body
swagger:model InitExportChildBlockBody
*/
type InitExportChildBlockBody struct {

	// first result pos
	FirstResultPos int64 `json:"firstResultPos,omitempty"`

	// include free blocks
	IncludeFreeBlocks bool `json:"includeFreeBlocks"`

	// page size
	PageSize int64 `json:"pageSize,omitempty"`

	// query
	Query string `json:"query,omitempty"`
}

// Validate validates this init export child block body
func (o *InitExportChildBlockBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *InitExportChildBlockBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *InitExportChildBlockBody) UnmarshalBinary(b []byte) error {
	var res InitExportChildBlockBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
