// Code generated by go-swagger; DO NOT EDIT.

package root_block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// EndExportRootBlockReader is a Reader for the EndExportRootBlock structure.
type EndExportRootBlockReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EndExportRootBlockReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEndExportRootBlockOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewEndExportRootBlockDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEndExportRootBlockOK creates a EndExportRootBlockOK with default headers values
func NewEndExportRootBlockOK() *EndExportRootBlockOK {
	return &EndExportRootBlockOK{}
}

/*EndExportRootBlockOK handles this case with default header values.

Exports of RootBlock completed
*/
type EndExportRootBlockOK struct {
}

func (o *EndExportRootBlockOK) Error() string {
	return fmt.Sprintf("[POST /Exports/endExportRootBlock][%d] endExportRootBlockOK ", 200)
}

func (o *EndExportRootBlockOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEndExportRootBlockDefault creates a EndExportRootBlockDefault with default headers values
func NewEndExportRootBlockDefault(code int) *EndExportRootBlockDefault {
	return &EndExportRootBlockDefault{
		_statusCode: code,
	}
}

/*EndExportRootBlockDefault handles this case with default header values.

Error response
*/
type EndExportRootBlockDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the end export root block default response
func (o *EndExportRootBlockDefault) Code() int {
	return o._statusCode
}

func (o *EndExportRootBlockDefault) Error() string {
	return fmt.Sprintf("[POST /Exports/endExportRootBlock][%d] endExportRootBlock default  %+v", o._statusCode, o.Payload)
}

func (o *EndExportRootBlockDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*EndExportRootBlockBody end export root block body
swagger:model EndExportRootBlockBody
*/
type EndExportRootBlockBody struct {

	// context
	Context *models.WSContext `json:"context,omitempty"`
}

// Validate validates this end export root block body
func (o *EndExportRootBlockBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateContext(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *EndExportRootBlockBody) validateContext(formats strfmt.Registry) error {

	if swag.IsZero(o.Context) { // not required
		return nil
	}

	if o.Context != nil {
		if err := o.Context.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("wscontext" + "." + "context")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *EndExportRootBlockBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *EndExportRootBlockBody) UnmarshalBinary(b []byte) error {
	var res EndExportRootBlockBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
