// Code generated by go-swagger; DO NOT EDIT.

package root_block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewEndExportRootBlockParams creates a new EndExportRootBlockParams object
// with the default values initialized.
func NewEndExportRootBlockParams() *EndExportRootBlockParams {
	var ()
	return &EndExportRootBlockParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEndExportRootBlockParamsWithTimeout creates a new EndExportRootBlockParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEndExportRootBlockParamsWithTimeout(timeout time.Duration) *EndExportRootBlockParams {
	var ()
	return &EndExportRootBlockParams{

		timeout: timeout,
	}
}

// NewEndExportRootBlockParamsWithContext creates a new EndExportRootBlockParams object
// with the default values initialized, and the ability to set a context for a request
func NewEndExportRootBlockParamsWithContext(ctx context.Context) *EndExportRootBlockParams {
	var ()
	return &EndExportRootBlockParams{

		Context: ctx,
	}
}

// NewEndExportRootBlockParamsWithHTTPClient creates a new EndExportRootBlockParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEndExportRootBlockParamsWithHTTPClient(client *http.Client) *EndExportRootBlockParams {
	var ()
	return &EndExportRootBlockParams{
		HTTPClient: client,
	}
}

/*EndExportRootBlockParams contains all the parameters to send to the API endpoint
for the end export root block operation typically these are written to a http.Request
*/
type EndExportRootBlockParams struct {

	/*Wscontext
	  The results from an exportRootBlock operation

	*/
	Wscontext EndExportRootBlockBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the end export root block params
func (o *EndExportRootBlockParams) WithTimeout(timeout time.Duration) *EndExportRootBlockParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the end export root block params
func (o *EndExportRootBlockParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the end export root block params
func (o *EndExportRootBlockParams) WithContext(ctx context.Context) *EndExportRootBlockParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the end export root block params
func (o *EndExportRootBlockParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the end export root block params
func (o *EndExportRootBlockParams) WithHTTPClient(client *http.Client) *EndExportRootBlockParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the end export root block params
func (o *EndExportRootBlockParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWscontext adds the wscontext to the end export root block params
func (o *EndExportRootBlockParams) WithWscontext(wscontext EndExportRootBlockBody) *EndExportRootBlockParams {
	o.SetWscontext(wscontext)
	return o
}

// SetWscontext adds the wscontext to the end export root block params
func (o *EndExportRootBlockParams) SetWscontext(wscontext EndExportRootBlockBody) {
	o.Wscontext = wscontext
}

// WriteToRequest writes these params to a swagger request
func (o *EndExportRootBlockParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Wscontext); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
