// Code generated by go-swagger; DO NOT EDIT.

package root_block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewExportRootBlockParams creates a new ExportRootBlockParams object
// with the default values initialized.
func NewExportRootBlockParams() *ExportRootBlockParams {
	var ()
	return &ExportRootBlockParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewExportRootBlockParamsWithTimeout creates a new ExportRootBlockParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewExportRootBlockParamsWithTimeout(timeout time.Duration) *ExportRootBlockParams {
	var ()
	return &ExportRootBlockParams{

		timeout: timeout,
	}
}

// NewExportRootBlockParamsWithContext creates a new ExportRootBlockParams object
// with the default values initialized, and the ability to set a context for a request
func NewExportRootBlockParamsWithContext(ctx context.Context) *ExportRootBlockParams {
	var ()
	return &ExportRootBlockParams{

		Context: ctx,
	}
}

// NewExportRootBlockParamsWithHTTPClient creates a new ExportRootBlockParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewExportRootBlockParamsWithHTTPClient(client *http.Client) *ExportRootBlockParams {
	var ()
	return &ExportRootBlockParams{
		HTTPClient: client,
	}
}

/*ExportRootBlockParams contains all the parameters to send to the API endpoint
for the export root block operation typically these are written to a http.Request
*/
type ExportRootBlockParams struct {

	/*Wscontext
	  The results from an initExportRootBlock operation

	*/
	Wscontext ExportRootBlockBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the export root block params
func (o *ExportRootBlockParams) WithTimeout(timeout time.Duration) *ExportRootBlockParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the export root block params
func (o *ExportRootBlockParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the export root block params
func (o *ExportRootBlockParams) WithContext(ctx context.Context) *ExportRootBlockParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the export root block params
func (o *ExportRootBlockParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the export root block params
func (o *ExportRootBlockParams) WithHTTPClient(client *http.Client) *ExportRootBlockParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the export root block params
func (o *ExportRootBlockParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWscontext adds the wscontext to the export root block params
func (o *ExportRootBlockParams) WithWscontext(wscontext ExportRootBlockBody) *ExportRootBlockParams {
	o.SetWscontext(wscontext)
	return o
}

// SetWscontext adds the wscontext to the export root block params
func (o *ExportRootBlockParams) SetWscontext(wscontext ExportRootBlockBody) {
	o.Wscontext = wscontext
}

// WriteToRequest writes these params to a swagger request
func (o *ExportRootBlockParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Wscontext); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
