// Code generated by go-swagger; DO NOT EDIT.

package block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteBlockParams creates a new DeleteBlockParams object
// with the default values initialized.
func NewDeleteBlockParams() *DeleteBlockParams {
	var ()
	return &DeleteBlockParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteBlockParamsWithTimeout creates a new DeleteBlockParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteBlockParamsWithTimeout(timeout time.Duration) *DeleteBlockParams {
	var ()
	return &DeleteBlockParams{

		timeout: timeout,
	}
}

// NewDeleteBlockParamsWithContext creates a new DeleteBlockParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteBlockParamsWithContext(ctx context.Context) *DeleteBlockParams {
	var ()
	return &DeleteBlockParams{

		Context: ctx,
	}
}

// NewDeleteBlockParamsWithHTTPClient creates a new DeleteBlockParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteBlockParamsWithHTTPClient(client *http.Client) *DeleteBlockParams {
	var ()
	return &DeleteBlockParams{
		HTTPClient: client,
	}
}

/*DeleteBlockParams contains all the parameters to send to the API endpoint
for the delete block operation typically these are written to a http.Request
*/
type DeleteBlockParams struct {

	/*DeleteParameters
	  Specify the blockName of the block to be deleted. container is required only when the blockName is not unique due to overlapping space.

	*/
	DeleteParameters DeleteBlockBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete block params
func (o *DeleteBlockParams) WithTimeout(timeout time.Duration) *DeleteBlockParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete block params
func (o *DeleteBlockParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete block params
func (o *DeleteBlockParams) WithContext(ctx context.Context) *DeleteBlockParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete block params
func (o *DeleteBlockParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete block params
func (o *DeleteBlockParams) WithHTTPClient(client *http.Client) *DeleteBlockParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete block params
func (o *DeleteBlockParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeleteParameters adds the deleteParameters to the delete block params
func (o *DeleteBlockParams) WithDeleteParameters(deleteParameters DeleteBlockBody) *DeleteBlockParams {
	o.SetDeleteParameters(deleteParameters)
	return o
}

// SetDeleteParameters adds the deleteParameters to the delete block params
func (o *DeleteBlockParams) SetDeleteParameters(deleteParameters DeleteBlockBody) {
	o.DeleteParameters = deleteParameters
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteBlockParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.DeleteParameters); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
