// Code generated by go-swagger; DO NOT EDIT.

package administrator_role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// ImportAdminRoleReader is a Reader for the ImportAdminRole structure.
type ImportAdminRoleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ImportAdminRoleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewImportAdminRoleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewImportAdminRoleDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewImportAdminRoleOK creates a ImportAdminRoleOK with default headers values
func NewImportAdminRoleOK() *ImportAdminRoleOK {
	return &ImportAdminRoleOK{}
}

/*ImportAdminRoleOK handles this case with default header values.

Imports of AdminRole completed
*/
type ImportAdminRoleOK struct {
	Payload *ImportAdminRoleOKBody
}

func (o *ImportAdminRoleOK) Error() string {
	return fmt.Sprintf("[POST /Imports/importAdminRole][%d] importAdminRoleOK  %+v", 200, o.Payload)
}

func (o *ImportAdminRoleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ImportAdminRoleOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewImportAdminRoleDefault creates a ImportAdminRoleDefault with default headers values
func NewImportAdminRoleDefault(code int) *ImportAdminRoleDefault {
	return &ImportAdminRoleDefault{
		_statusCode: code,
	}
}

/*ImportAdminRoleDefault handles this case with default header values.

Error response
*/
type ImportAdminRoleDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the import admin role default response
func (o *ImportAdminRoleDefault) Code() int {
	return o._statusCode
}

func (o *ImportAdminRoleDefault) Error() string {
	return fmt.Sprintf("[POST /Imports/importAdminRole][%d] importAdminRole default  %+v", o._statusCode, o.Payload)
}

func (o *ImportAdminRoleDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ImportAdminRoleBody import admin role body
swagger:model ImportAdminRoleBody
*/
type ImportAdminRoleBody struct {

	// wsadmin role
	WsadminRole *models.WSAdminRole `json:"wsadminRole,omitempty"`
}

// Validate validates this import admin role body
func (o *ImportAdminRoleBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateWsadminRole(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ImportAdminRoleBody) validateWsadminRole(formats strfmt.Registry) error {

	if swag.IsZero(o.WsadminRole) { // not required
		return nil
	}

	if o.WsadminRole != nil {
		if err := o.WsadminRole.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Import Parameters" + "." + "wsadminRole")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ImportAdminRoleBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ImportAdminRoleBody) UnmarshalBinary(b []byte) error {
	var res ImportAdminRoleBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*ImportAdminRoleOKBody import admin role o k body
swagger:model ImportAdminRoleOKBody
*/
type ImportAdminRoleOKBody struct {

	// result
	Result string `json:"result,omitempty"`
}

// Validate validates this import admin role o k body
func (o *ImportAdminRoleOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ImportAdminRoleOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ImportAdminRoleOKBody) UnmarshalBinary(b []byte) error {
	var res ImportAdminRoleOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
