// Code generated by go-swagger; DO NOT EDIT.

package administrator_role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewInitExportAdminRoleParams creates a new InitExportAdminRoleParams object
// with the default values initialized.
func NewInitExportAdminRoleParams() *InitExportAdminRoleParams {
	var ()
	return &InitExportAdminRoleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewInitExportAdminRoleParamsWithTimeout creates a new InitExportAdminRoleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewInitExportAdminRoleParamsWithTimeout(timeout time.Duration) *InitExportAdminRoleParams {
	var ()
	return &InitExportAdminRoleParams{

		timeout: timeout,
	}
}

// NewInitExportAdminRoleParamsWithContext creates a new InitExportAdminRoleParams object
// with the default values initialized, and the ability to set a context for a request
func NewInitExportAdminRoleParamsWithContext(ctx context.Context) *InitExportAdminRoleParams {
	var ()
	return &InitExportAdminRoleParams{

		Context: ctx,
	}
}

// NewInitExportAdminRoleParamsWithHTTPClient creates a new InitExportAdminRoleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewInitExportAdminRoleParamsWithHTTPClient(client *http.Client) *InitExportAdminRoleParams {
	var ()
	return &InitExportAdminRoleParams{
		HTTPClient: client,
	}
}

/*InitExportAdminRoleParams contains all the parameters to send to the API endpoint
for the init export admin role operation typically these are written to a http.Request
*/
type InitExportAdminRoleParams struct {

	/*ExportParameters
	  The query string syntax and supported selectors are defined in the IPControl CLI and API Guide. Use pageSize to specify the number of results to be returned. Use firstResultPos to indicate where the set of results should begin. Results begin at position 0.

	*/
	ExportParameters InitExportAdminRoleBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the init export admin role params
func (o *InitExportAdminRoleParams) WithTimeout(timeout time.Duration) *InitExportAdminRoleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the init export admin role params
func (o *InitExportAdminRoleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the init export admin role params
func (o *InitExportAdminRoleParams) WithContext(ctx context.Context) *InitExportAdminRoleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the init export admin role params
func (o *InitExportAdminRoleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the init export admin role params
func (o *InitExportAdminRoleParams) WithHTTPClient(client *http.Client) *InitExportAdminRoleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the init export admin role params
func (o *InitExportAdminRoleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithExportParameters adds the exportParameters to the init export admin role params
func (o *InitExportAdminRoleParams) WithExportParameters(exportParameters InitExportAdminRoleBody) *InitExportAdminRoleParams {
	o.SetExportParameters(exportParameters)
	return o
}

// SetExportParameters adds the exportParameters to the init export admin role params
func (o *InitExportAdminRoleParams) SetExportParameters(exportParameters InitExportAdminRoleBody) {
	o.ExportParameters = exportParameters
}

// WriteToRequest writes these params to a swagger request
func (o *InitExportAdminRoleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.ExportParameters); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
