// Code generated by go-swagger; DO NOT EDIT.

package zone

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// ImportDNSZoneReader is a Reader for the ImportDNSZone structure.
type ImportDNSZoneReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ImportDNSZoneReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewImportDNSZoneOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewImportDNSZoneDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewImportDNSZoneOK creates a ImportDNSZoneOK with default headers values
func NewImportDNSZoneOK() *ImportDNSZoneOK {
	return &ImportDNSZoneOK{}
}

/*ImportDNSZoneOK handles this case with default header values.

Imports of DnsZone completed
*/
type ImportDNSZoneOK struct {
}

func (o *ImportDNSZoneOK) Error() string {
	return fmt.Sprintf("[POST /Imports/importDnsZone][%d] importDnsZoneOK ", 200)
}

func (o *ImportDNSZoneOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewImportDNSZoneDefault creates a ImportDNSZoneDefault with default headers values
func NewImportDNSZoneDefault(code int) *ImportDNSZoneDefault {
	return &ImportDNSZoneDefault{
		_statusCode: code,
	}
}

/*ImportDNSZoneDefault handles this case with default header values.

Error response
*/
type ImportDNSZoneDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the import Dns zone default response
func (o *ImportDNSZoneDefault) Code() int {
	return o._statusCode
}

func (o *ImportDNSZoneDefault) Error() string {
	return fmt.Sprintf("[POST /Imports/importDnsZone][%d] importDnsZone default  %+v", o._statusCode, o.Payload)
}

func (o *ImportDNSZoneDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ImportDNSZoneBody import DNS zone body
swagger:model ImportDNSZoneBody
*/
type ImportDNSZoneBody struct {

	// inp zone
	InpZone *models.WSDNSZone `json:"inpZone,omitempty"`
}

// Validate validates this import DNS zone body
func (o *ImportDNSZoneBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateInpZone(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ImportDNSZoneBody) validateInpZone(formats strfmt.Registry) error {

	if swag.IsZero(o.InpZone) { // not required
		return nil
	}

	if o.InpZone != nil {
		if err := o.InpZone.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Import Parameters" + "." + "inpZone")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ImportDNSZoneBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ImportDNSZoneBody) UnmarshalBinary(b []byte) error {
	var res ImportDNSZoneBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
