// Code generated by go-swagger; DO NOT EDIT.

package pending_approval

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// EndExportResourceRecordPendingApprovalStatusReader is a Reader for the EndExportResourceRecordPendingApprovalStatus structure.
type EndExportResourceRecordPendingApprovalStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EndExportResourceRecordPendingApprovalStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEndExportResourceRecordPendingApprovalStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewEndExportResourceRecordPendingApprovalStatusDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEndExportResourceRecordPendingApprovalStatusOK creates a EndExportResourceRecordPendingApprovalStatusOK with default headers values
func NewEndExportResourceRecordPendingApprovalStatusOK() *EndExportResourceRecordPendingApprovalStatusOK {
	return &EndExportResourceRecordPendingApprovalStatusOK{}
}

/*EndExportResourceRecordPendingApprovalStatusOK handles this case with default header values.

Exports of ResourceRecordPendingApprovalStatus completed
*/
type EndExportResourceRecordPendingApprovalStatusOK struct {
}

func (o *EndExportResourceRecordPendingApprovalStatusOK) Error() string {
	return fmt.Sprintf("[POST /Exports/endExportResourceRecordPendingApprovalStatus][%d] endExportResourceRecordPendingApprovalStatusOK ", 200)
}

func (o *EndExportResourceRecordPendingApprovalStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEndExportResourceRecordPendingApprovalStatusDefault creates a EndExportResourceRecordPendingApprovalStatusDefault with default headers values
func NewEndExportResourceRecordPendingApprovalStatusDefault(code int) *EndExportResourceRecordPendingApprovalStatusDefault {
	return &EndExportResourceRecordPendingApprovalStatusDefault{
		_statusCode: code,
	}
}

/*EndExportResourceRecordPendingApprovalStatusDefault handles this case with default header values.

Error response
*/
type EndExportResourceRecordPendingApprovalStatusDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the end export resource record pending approval status default response
func (o *EndExportResourceRecordPendingApprovalStatusDefault) Code() int {
	return o._statusCode
}

func (o *EndExportResourceRecordPendingApprovalStatusDefault) Error() string {
	return fmt.Sprintf("[POST /Exports/endExportResourceRecordPendingApprovalStatus][%d] endExportResourceRecordPendingApprovalStatus default  %+v", o._statusCode, o.Payload)
}

func (o *EndExportResourceRecordPendingApprovalStatusDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*EndExportResourceRecordPendingApprovalStatusBody end export resource record pending approval status body
swagger:model EndExportResourceRecordPendingApprovalStatusBody
*/
type EndExportResourceRecordPendingApprovalStatusBody struct {

	// context
	Context *models.WSContext `json:"context,omitempty"`
}

// Validate validates this end export resource record pending approval status body
func (o *EndExportResourceRecordPendingApprovalStatusBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateContext(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *EndExportResourceRecordPendingApprovalStatusBody) validateContext(formats strfmt.Registry) error {

	if swag.IsZero(o.Context) { // not required
		return nil
	}

	if o.Context != nil {
		if err := o.Context.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("wscontext" + "." + "context")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *EndExportResourceRecordPendingApprovalStatusBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *EndExportResourceRecordPendingApprovalStatusBody) UnmarshalBinary(b []byte) error {
	var res EndExportResourceRecordPendingApprovalStatusBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
