// Code generated by go-swagger; DO NOT EDIT.

package pending_approval

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewEndExportResourceRecordPendingApprovalStatusParams creates a new EndExportResourceRecordPendingApprovalStatusParams object
// with the default values initialized.
func NewEndExportResourceRecordPendingApprovalStatusParams() *EndExportResourceRecordPendingApprovalStatusParams {
	var ()
	return &EndExportResourceRecordPendingApprovalStatusParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEndExportResourceRecordPendingApprovalStatusParamsWithTimeout creates a new EndExportResourceRecordPendingApprovalStatusParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEndExportResourceRecordPendingApprovalStatusParamsWithTimeout(timeout time.Duration) *EndExportResourceRecordPendingApprovalStatusParams {
	var ()
	return &EndExportResourceRecordPendingApprovalStatusParams{

		timeout: timeout,
	}
}

// NewEndExportResourceRecordPendingApprovalStatusParamsWithContext creates a new EndExportResourceRecordPendingApprovalStatusParams object
// with the default values initialized, and the ability to set a context for a request
func NewEndExportResourceRecordPendingApprovalStatusParamsWithContext(ctx context.Context) *EndExportResourceRecordPendingApprovalStatusParams {
	var ()
	return &EndExportResourceRecordPendingApprovalStatusParams{

		Context: ctx,
	}
}

// NewEndExportResourceRecordPendingApprovalStatusParamsWithHTTPClient creates a new EndExportResourceRecordPendingApprovalStatusParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEndExportResourceRecordPendingApprovalStatusParamsWithHTTPClient(client *http.Client) *EndExportResourceRecordPendingApprovalStatusParams {
	var ()
	return &EndExportResourceRecordPendingApprovalStatusParams{
		HTTPClient: client,
	}
}

/*EndExportResourceRecordPendingApprovalStatusParams contains all the parameters to send to the API endpoint
for the end export resource record pending approval status operation typically these are written to a http.Request
*/
type EndExportResourceRecordPendingApprovalStatusParams struct {

	/*Wscontext
	  The results from an exportResourceRecordPendingApprovalStatus operation

	*/
	Wscontext EndExportResourceRecordPendingApprovalStatusBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the end export resource record pending approval status params
func (o *EndExportResourceRecordPendingApprovalStatusParams) WithTimeout(timeout time.Duration) *EndExportResourceRecordPendingApprovalStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the end export resource record pending approval status params
func (o *EndExportResourceRecordPendingApprovalStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the end export resource record pending approval status params
func (o *EndExportResourceRecordPendingApprovalStatusParams) WithContext(ctx context.Context) *EndExportResourceRecordPendingApprovalStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the end export resource record pending approval status params
func (o *EndExportResourceRecordPendingApprovalStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the end export resource record pending approval status params
func (o *EndExportResourceRecordPendingApprovalStatusParams) WithHTTPClient(client *http.Client) *EndExportResourceRecordPendingApprovalStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the end export resource record pending approval status params
func (o *EndExportResourceRecordPendingApprovalStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWscontext adds the wscontext to the end export resource record pending approval status params
func (o *EndExportResourceRecordPendingApprovalStatusParams) WithWscontext(wscontext EndExportResourceRecordPendingApprovalStatusBody) *EndExportResourceRecordPendingApprovalStatusParams {
	o.SetWscontext(wscontext)
	return o
}

// SetWscontext adds the wscontext to the end export resource record pending approval status params
func (o *EndExportResourceRecordPendingApprovalStatusParams) SetWscontext(wscontext EndExportResourceRecordPendingApprovalStatusBody) {
	o.Wscontext = wscontext
}

// WriteToRequest writes these params to a swagger request
func (o *EndExportResourceRecordPendingApprovalStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Wscontext); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
