// Code generated by go-swagger; DO NOT EDIT.

package pending_approval

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewEndExportResourceRecordPendingApprovalParams creates a new EndExportResourceRecordPendingApprovalParams object
// with the default values initialized.
func NewEndExportResourceRecordPendingApprovalParams() *EndExportResourceRecordPendingApprovalParams {
	var ()
	return &EndExportResourceRecordPendingApprovalParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEndExportResourceRecordPendingApprovalParamsWithTimeout creates a new EndExportResourceRecordPendingApprovalParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEndExportResourceRecordPendingApprovalParamsWithTimeout(timeout time.Duration) *EndExportResourceRecordPendingApprovalParams {
	var ()
	return &EndExportResourceRecordPendingApprovalParams{

		timeout: timeout,
	}
}

// NewEndExportResourceRecordPendingApprovalParamsWithContext creates a new EndExportResourceRecordPendingApprovalParams object
// with the default values initialized, and the ability to set a context for a request
func NewEndExportResourceRecordPendingApprovalParamsWithContext(ctx context.Context) *EndExportResourceRecordPendingApprovalParams {
	var ()
	return &EndExportResourceRecordPendingApprovalParams{

		Context: ctx,
	}
}

// NewEndExportResourceRecordPendingApprovalParamsWithHTTPClient creates a new EndExportResourceRecordPendingApprovalParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEndExportResourceRecordPendingApprovalParamsWithHTTPClient(client *http.Client) *EndExportResourceRecordPendingApprovalParams {
	var ()
	return &EndExportResourceRecordPendingApprovalParams{
		HTTPClient: client,
	}
}

/*EndExportResourceRecordPendingApprovalParams contains all the parameters to send to the API endpoint
for the end export resource record pending approval operation typically these are written to a http.Request
*/
type EndExportResourceRecordPendingApprovalParams struct {

	/*Wscontext
	  The results from an exportResourceRecordPendingApproval operation

	*/
	Wscontext EndExportResourceRecordPendingApprovalBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the end export resource record pending approval params
func (o *EndExportResourceRecordPendingApprovalParams) WithTimeout(timeout time.Duration) *EndExportResourceRecordPendingApprovalParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the end export resource record pending approval params
func (o *EndExportResourceRecordPendingApprovalParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the end export resource record pending approval params
func (o *EndExportResourceRecordPendingApprovalParams) WithContext(ctx context.Context) *EndExportResourceRecordPendingApprovalParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the end export resource record pending approval params
func (o *EndExportResourceRecordPendingApprovalParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the end export resource record pending approval params
func (o *EndExportResourceRecordPendingApprovalParams) WithHTTPClient(client *http.Client) *EndExportResourceRecordPendingApprovalParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the end export resource record pending approval params
func (o *EndExportResourceRecordPendingApprovalParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWscontext adds the wscontext to the end export resource record pending approval params
func (o *EndExportResourceRecordPendingApprovalParams) WithWscontext(wscontext EndExportResourceRecordPendingApprovalBody) *EndExportResourceRecordPendingApprovalParams {
	o.SetWscontext(wscontext)
	return o
}

// SetWscontext adds the wscontext to the end export resource record pending approval params
func (o *EndExportResourceRecordPendingApprovalParams) SetWscontext(wscontext EndExportResourceRecordPendingApprovalBody) {
	o.Wscontext = wscontext
}

// WriteToRequest writes these params to a swagger request
func (o *EndExportResourceRecordPendingApprovalParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Wscontext); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
