// Code generated by go-swagger; DO NOT EDIT.

package pending_approval

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewExportResourceRecordPendingApprovalStatusParams creates a new ExportResourceRecordPendingApprovalStatusParams object
// with the default values initialized.
func NewExportResourceRecordPendingApprovalStatusParams() *ExportResourceRecordPendingApprovalStatusParams {
	var ()
	return &ExportResourceRecordPendingApprovalStatusParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewExportResourceRecordPendingApprovalStatusParamsWithTimeout creates a new ExportResourceRecordPendingApprovalStatusParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewExportResourceRecordPendingApprovalStatusParamsWithTimeout(timeout time.Duration) *ExportResourceRecordPendingApprovalStatusParams {
	var ()
	return &ExportResourceRecordPendingApprovalStatusParams{

		timeout: timeout,
	}
}

// NewExportResourceRecordPendingApprovalStatusParamsWithContext creates a new ExportResourceRecordPendingApprovalStatusParams object
// with the default values initialized, and the ability to set a context for a request
func NewExportResourceRecordPendingApprovalStatusParamsWithContext(ctx context.Context) *ExportResourceRecordPendingApprovalStatusParams {
	var ()
	return &ExportResourceRecordPendingApprovalStatusParams{

		Context: ctx,
	}
}

// NewExportResourceRecordPendingApprovalStatusParamsWithHTTPClient creates a new ExportResourceRecordPendingApprovalStatusParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewExportResourceRecordPendingApprovalStatusParamsWithHTTPClient(client *http.Client) *ExportResourceRecordPendingApprovalStatusParams {
	var ()
	return &ExportResourceRecordPendingApprovalStatusParams{
		HTTPClient: client,
	}
}

/*ExportResourceRecordPendingApprovalStatusParams contains all the parameters to send to the API endpoint
for the export resource record pending approval status operation typically these are written to a http.Request
*/
type ExportResourceRecordPendingApprovalStatusParams struct {

	/*Wscontext
	  The results from an initExportResourceRecordPendingApprovalStatus operation

	*/
	Wscontext ExportResourceRecordPendingApprovalStatusBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the export resource record pending approval status params
func (o *ExportResourceRecordPendingApprovalStatusParams) WithTimeout(timeout time.Duration) *ExportResourceRecordPendingApprovalStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the export resource record pending approval status params
func (o *ExportResourceRecordPendingApprovalStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the export resource record pending approval status params
func (o *ExportResourceRecordPendingApprovalStatusParams) WithContext(ctx context.Context) *ExportResourceRecordPendingApprovalStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the export resource record pending approval status params
func (o *ExportResourceRecordPendingApprovalStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the export resource record pending approval status params
func (o *ExportResourceRecordPendingApprovalStatusParams) WithHTTPClient(client *http.Client) *ExportResourceRecordPendingApprovalStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the export resource record pending approval status params
func (o *ExportResourceRecordPendingApprovalStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWscontext adds the wscontext to the export resource record pending approval status params
func (o *ExportResourceRecordPendingApprovalStatusParams) WithWscontext(wscontext ExportResourceRecordPendingApprovalStatusBody) *ExportResourceRecordPendingApprovalStatusParams {
	o.SetWscontext(wscontext)
	return o
}

// SetWscontext adds the wscontext to the export resource record pending approval status params
func (o *ExportResourceRecordPendingApprovalStatusParams) SetWscontext(wscontext ExportResourceRecordPendingApprovalStatusBody) {
	o.Wscontext = wscontext
}

// WriteToRequest writes these params to a swagger request
func (o *ExportResourceRecordPendingApprovalStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Wscontext); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
