// Code generated by go-swagger; DO NOT EDIT.

package domain

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// ImportGalaxyDomainReader is a Reader for the ImportGalaxyDomain structure.
type ImportGalaxyDomainReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ImportGalaxyDomainReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewImportGalaxyDomainOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewImportGalaxyDomainDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewImportGalaxyDomainOK creates a ImportGalaxyDomainOK with default headers values
func NewImportGalaxyDomainOK() *ImportGalaxyDomainOK {
	return &ImportGalaxyDomainOK{}
}

/*ImportGalaxyDomainOK handles this case with default header values.

Imports of GalaxyDomain completed
*/
type ImportGalaxyDomainOK struct {
}

func (o *ImportGalaxyDomainOK) Error() string {
	return fmt.Sprintf("[POST /Imports/importGalaxyDomain][%d] importGalaxyDomainOK ", 200)
}

func (o *ImportGalaxyDomainOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewImportGalaxyDomainDefault creates a ImportGalaxyDomainDefault with default headers values
func NewImportGalaxyDomainDefault(code int) *ImportGalaxyDomainDefault {
	return &ImportGalaxyDomainDefault{
		_statusCode: code,
	}
}

/*ImportGalaxyDomainDefault handles this case with default header values.

Error response
*/
type ImportGalaxyDomainDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the import galaxy domain default response
func (o *ImportGalaxyDomainDefault) Code() int {
	return o._statusCode
}

func (o *ImportGalaxyDomainDefault) Error() string {
	return fmt.Sprintf("[POST /Imports/importGalaxyDomain][%d] importGalaxyDomain default  %+v", o._statusCode, o.Payload)
}

func (o *ImportGalaxyDomainDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ImportGalaxyDomainBody import galaxy domain body
swagger:model ImportGalaxyDomainBody
*/
type ImportGalaxyDomainBody struct {

	// inp galaxy domain
	InpGalaxyDomain *models.WSGalaxyDomain `json:"inpGalaxyDomain,omitempty"`
}

// Validate validates this import galaxy domain body
func (o *ImportGalaxyDomainBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateInpGalaxyDomain(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ImportGalaxyDomainBody) validateInpGalaxyDomain(formats strfmt.Registry) error {

	if swag.IsZero(o.InpGalaxyDomain) { // not required
		return nil
	}

	if o.InpGalaxyDomain != nil {
		if err := o.InpGalaxyDomain.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Import Parameters" + "." + "inpGalaxyDomain")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ImportGalaxyDomainBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ImportGalaxyDomainBody) UnmarshalBinary(b []byte) error {
	var res ImportGalaxyDomainBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
