// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// ExportDeviceRestoreListReader is a Reader for the ExportDeviceRestoreList structure.
type ExportDeviceRestoreListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExportDeviceRestoreListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewExportDeviceRestoreListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewExportDeviceRestoreListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewExportDeviceRestoreListOK creates a ExportDeviceRestoreListOK with default headers values
func NewExportDeviceRestoreListOK() *ExportDeviceRestoreListOK {
	return &ExportDeviceRestoreListOK{}
}

/*ExportDeviceRestoreListOK handles this case with default header values.

DeviceRestoreList returned
*/
type ExportDeviceRestoreListOK struct {
	Payload []*models.WSRestoreDevice
}

func (o *ExportDeviceRestoreListOK) Error() string {
	return fmt.Sprintf("[POST /Exports/exportDeviceRestoreList][%d] exportDeviceRestoreListOK  %+v", 200, o.Payload)
}

func (o *ExportDeviceRestoreListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExportDeviceRestoreListDefault creates a ExportDeviceRestoreListDefault with default headers values
func NewExportDeviceRestoreListDefault(code int) *ExportDeviceRestoreListDefault {
	return &ExportDeviceRestoreListDefault{
		_statusCode: code,
	}
}

/*ExportDeviceRestoreListDefault handles this case with default header values.

Error response
*/
type ExportDeviceRestoreListDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the export device restore list default response
func (o *ExportDeviceRestoreListDefault) Code() int {
	return o._statusCode
}

func (o *ExportDeviceRestoreListDefault) Error() string {
	return fmt.Sprintf("[POST /Exports/exportDeviceRestoreList][%d] exportDeviceRestoreList default  %+v", o._statusCode, o.Payload)
}

func (o *ExportDeviceRestoreListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ExportDeviceRestoreListBody export device restore list body
swagger:model ExportDeviceRestoreListBody
*/
type ExportDeviceRestoreListBody struct {

	// context
	Context *models.WSContext `json:"context,omitempty"`
}

// Validate validates this export device restore list body
func (o *ExportDeviceRestoreListBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateContext(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ExportDeviceRestoreListBody) validateContext(formats strfmt.Registry) error {

	if swag.IsZero(o.Context) { // not required
		return nil
	}

	if o.Context != nil {
		if err := o.Context.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("wscontext" + "." + "context")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ExportDeviceRestoreListBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ExportDeviceRestoreListBody) UnmarshalBinary(b []byte) error {
	var res ExportDeviceRestoreListBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
