// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// InitExportDeviceUDFTagsReader is a Reader for the InitExportDeviceUDFTags structure.
type InitExportDeviceUDFTagsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InitExportDeviceUDFTagsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewInitExportDeviceUDFTagsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewInitExportDeviceUDFTagsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewInitExportDeviceUDFTagsOK creates a InitExportDeviceUDFTagsOK with default headers values
func NewInitExportDeviceUDFTagsOK() *InitExportDeviceUDFTagsOK {
	return &InitExportDeviceUDFTagsOK{}
}

/*InitExportDeviceUDFTagsOK handles this case with default header values.

Exports of DeviceUDFTags initialized
*/
type InitExportDeviceUDFTagsOK struct {
	Payload []string
}

func (o *InitExportDeviceUDFTagsOK) Error() string {
	return fmt.Sprintf("[POST /Exports/initExportDeviceUDFTags][%d] initExportDeviceUDFTagsOK  %+v", 200, o.Payload)
}

func (o *InitExportDeviceUDFTagsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewInitExportDeviceUDFTagsDefault creates a InitExportDeviceUDFTagsDefault with default headers values
func NewInitExportDeviceUDFTagsDefault(code int) *InitExportDeviceUDFTagsDefault {
	return &InitExportDeviceUDFTagsDefault{
		_statusCode: code,
	}
}

/*InitExportDeviceUDFTagsDefault handles this case with default header values.

Error response
*/
type InitExportDeviceUDFTagsDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the init export device u d f tags default response
func (o *InitExportDeviceUDFTagsDefault) Code() int {
	return o._statusCode
}

func (o *InitExportDeviceUDFTagsDefault) Error() string {
	return fmt.Sprintf("[POST /Exports/initExportDeviceUDFTags][%d] initExportDeviceUDFTags default  %+v", o._statusCode, o.Payload)
}

func (o *InitExportDeviceUDFTagsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*InitExportDeviceUDFTagsBody init export device u d f tags body
swagger:model InitExportDeviceUDFTagsBody
*/
type InitExportDeviceUDFTagsBody struct {

	// context
	Context *models.WSContext `json:"context,omitempty"`

	// first result pos
	FirstResultPos int64 `json:"firstResultPos,omitempty"`

	// page size
	PageSize int64 `json:"pageSize,omitempty"`
}

// Validate validates this init export device u d f tags body
func (o *InitExportDeviceUDFTagsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateContext(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *InitExportDeviceUDFTagsBody) validateContext(formats strfmt.Registry) error {

	if swag.IsZero(o.Context) { // not required
		return nil
	}

	if o.Context != nil {
		if err := o.Context.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("wscontext" + "." + "context")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *InitExportDeviceUDFTagsBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *InitExportDeviceUDFTagsBody) UnmarshalBinary(b []byte) error {
	var res InitExportDeviceUDFTagsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
