// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// InitExportDeviceRestoreListReader is a Reader for the InitExportDeviceRestoreList structure.
type InitExportDeviceRestoreListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InitExportDeviceRestoreListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewInitExportDeviceRestoreListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewInitExportDeviceRestoreListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewInitExportDeviceRestoreListOK creates a InitExportDeviceRestoreListOK with default headers values
func NewInitExportDeviceRestoreListOK() *InitExportDeviceRestoreListOK {
	return &InitExportDeviceRestoreListOK{}
}

/*InitExportDeviceRestoreListOK handles this case with default header values.

Exports of DeviceRestoreList initialized
*/
type InitExportDeviceRestoreListOK struct {
	Payload *models.WSContext
}

func (o *InitExportDeviceRestoreListOK) Error() string {
	return fmt.Sprintf("[POST /Exports/initExportDeviceRestoreList][%d] initExportDeviceRestoreListOK  %+v", 200, o.Payload)
}

func (o *InitExportDeviceRestoreListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WSContext)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewInitExportDeviceRestoreListDefault creates a InitExportDeviceRestoreListDefault with default headers values
func NewInitExportDeviceRestoreListDefault(code int) *InitExportDeviceRestoreListDefault {
	return &InitExportDeviceRestoreListDefault{
		_statusCode: code,
	}
}

/*InitExportDeviceRestoreListDefault handles this case with default header values.

Error response
*/
type InitExportDeviceRestoreListDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the init export device restore list default response
func (o *InitExportDeviceRestoreListDefault) Code() int {
	return o._statusCode
}

func (o *InitExportDeviceRestoreListDefault) Error() string {
	return fmt.Sprintf("[POST /Exports/initExportDeviceRestoreList][%d] initExportDeviceRestoreList default  %+v", o._statusCode, o.Payload)
}

func (o *InitExportDeviceRestoreListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*InitExportDeviceRestoreListBody init export device restore list body
swagger:model InitExportDeviceRestoreListBody
*/
type InitExportDeviceRestoreListBody struct {

	// filter
	Filter string `json:"filter,omitempty"`

	// first result pos
	FirstResultPos int64 `json:"firstResultPos,omitempty"`

	// options
	Options []string `json:"options"`

	// page size
	PageSize int64 `json:"pageSize,omitempty"`
}

// Validate validates this init export device restore list body
func (o *InitExportDeviceRestoreListBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *InitExportDeviceRestoreListBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *InitExportDeviceRestoreListBody) UnmarshalBinary(b []byte) error {
	var res InitExportDeviceRestoreListBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
