// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewInitExportDeviceParams creates a new InitExportDeviceParams object
// with the default values initialized.
func NewInitExportDeviceParams() *InitExportDeviceParams {
	var ()
	return &InitExportDeviceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewInitExportDeviceParamsWithTimeout creates a new InitExportDeviceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewInitExportDeviceParamsWithTimeout(timeout time.Duration) *InitExportDeviceParams {
	var ()
	return &InitExportDeviceParams{

		timeout: timeout,
	}
}

// NewInitExportDeviceParamsWithContext creates a new InitExportDeviceParams object
// with the default values initialized, and the ability to set a context for a request
func NewInitExportDeviceParamsWithContext(ctx context.Context) *InitExportDeviceParams {
	var ()
	return &InitExportDeviceParams{

		Context: ctx,
	}
}

// NewInitExportDeviceParamsWithHTTPClient creates a new InitExportDeviceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewInitExportDeviceParamsWithHTTPClient(client *http.Client) *InitExportDeviceParams {
	var ()
	return &InitExportDeviceParams{
		HTTPClient: client,
	}
}

/*InitExportDeviceParams contains all the parameters to send to the API endpoint
for the init export device operation typically these are written to a http.Request
*/
type InitExportDeviceParams struct {

	/*ExportParameters
	  The query string syntax and supported selectors are defined in the IPControl CLI and API Guide. Use pageSize to specify the number of results to be returned. Use firstResultPos to indicate where the set of results should begin. Results begin at position 0. recurseContainerHierarchy is the only supported option for this operation.

	*/
	ExportParameters InitExportDeviceBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the init export device params
func (o *InitExportDeviceParams) WithTimeout(timeout time.Duration) *InitExportDeviceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the init export device params
func (o *InitExportDeviceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the init export device params
func (o *InitExportDeviceParams) WithContext(ctx context.Context) *InitExportDeviceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the init export device params
func (o *InitExportDeviceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the init export device params
func (o *InitExportDeviceParams) WithHTTPClient(client *http.Client) *InitExportDeviceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the init export device params
func (o *InitExportDeviceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithExportParameters adds the exportParameters to the init export device params
func (o *InitExportDeviceParams) WithExportParameters(exportParameters InitExportDeviceBody) *InitExportDeviceParams {
	o.SetExportParameters(exportParameters)
	return o
}

// SetExportParameters adds the exportParameters to the init export device params
func (o *InitExportDeviceParams) SetExportParameters(exportParameters InitExportDeviceBody) {
	o.ExportParameters = exportParameters
}

// WriteToRequest writes these params to a swagger request
func (o *InitExportDeviceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.ExportParameters); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
