// Code generated by go-swagger; DO NOT EDIT.

package network_link

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// ExportNetworkLinkReader is a Reader for the ExportNetworkLink structure.
type ExportNetworkLinkReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExportNetworkLinkReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewExportNetworkLinkOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewExportNetworkLinkDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewExportNetworkLinkOK creates a ExportNetworkLinkOK with default headers values
func NewExportNetworkLinkOK() *ExportNetworkLinkOK {
	return &ExportNetworkLinkOK{}
}

/*ExportNetworkLinkOK handles this case with default header values.

NetworkLink returned
*/
type ExportNetworkLinkOK struct {
	Payload []*models.WSNetworkLink
}

func (o *ExportNetworkLinkOK) Error() string {
	return fmt.Sprintf("[POST /Exports/exportNetworkLink][%d] exportNetworkLinkOK  %+v", 200, o.Payload)
}

func (o *ExportNetworkLinkOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExportNetworkLinkDefault creates a ExportNetworkLinkDefault with default headers values
func NewExportNetworkLinkDefault(code int) *ExportNetworkLinkDefault {
	return &ExportNetworkLinkDefault{
		_statusCode: code,
	}
}

/*ExportNetworkLinkDefault handles this case with default header values.

Error response
*/
type ExportNetworkLinkDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the export network link default response
func (o *ExportNetworkLinkDefault) Code() int {
	return o._statusCode
}

func (o *ExportNetworkLinkDefault) Error() string {
	return fmt.Sprintf("[POST /Exports/exportNetworkLink][%d] exportNetworkLink default  %+v", o._statusCode, o.Payload)
}

func (o *ExportNetworkLinkDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ExportNetworkLinkBody export network link body
swagger:model ExportNetworkLinkBody
*/
type ExportNetworkLinkBody struct {

	// context
	Context *models.WSContext `json:"context,omitempty"`
}

// Validate validates this export network link body
func (o *ExportNetworkLinkBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateContext(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ExportNetworkLinkBody) validateContext(formats strfmt.Registry) error {

	if swag.IsZero(o.Context) { // not required
		return nil
	}

	if o.Context != nil {
		if err := o.Context.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("wscontext" + "." + "context")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ExportNetworkLinkBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ExportNetworkLinkBody) UnmarshalBinary(b []byte) error {
	var res ExportNetworkLinkBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
