// Code generated by go-swagger; DO NOT EDIT.

package network_link

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewImportNetworkLinkParams creates a new ImportNetworkLinkParams object
// with the default values initialized.
func NewImportNetworkLinkParams() *ImportNetworkLinkParams {
	var ()
	return &ImportNetworkLinkParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewImportNetworkLinkParamsWithTimeout creates a new ImportNetworkLinkParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewImportNetworkLinkParamsWithTimeout(timeout time.Duration) *ImportNetworkLinkParams {
	var ()
	return &ImportNetworkLinkParams{

		timeout: timeout,
	}
}

// NewImportNetworkLinkParamsWithContext creates a new ImportNetworkLinkParams object
// with the default values initialized, and the ability to set a context for a request
func NewImportNetworkLinkParamsWithContext(ctx context.Context) *ImportNetworkLinkParams {
	var ()
	return &ImportNetworkLinkParams{

		Context: ctx,
	}
}

// NewImportNetworkLinkParamsWithHTTPClient creates a new ImportNetworkLinkParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewImportNetworkLinkParamsWithHTTPClient(client *http.Client) *ImportNetworkLinkParams {
	var ()
	return &ImportNetworkLinkParams{
		HTTPClient: client,
	}
}

/*ImportNetworkLinkParams contains all the parameters to send to the API endpoint
for the import network link operation typically these are written to a http.Request
*/
type ImportNetworkLinkParams struct {

	/*ImportParameters
	  The input describing the network link to be imported. The name parameter is required.

	*/
	ImportParameters ImportNetworkLinkBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the import network link params
func (o *ImportNetworkLinkParams) WithTimeout(timeout time.Duration) *ImportNetworkLinkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the import network link params
func (o *ImportNetworkLinkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the import network link params
func (o *ImportNetworkLinkParams) WithContext(ctx context.Context) *ImportNetworkLinkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the import network link params
func (o *ImportNetworkLinkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the import network link params
func (o *ImportNetworkLinkParams) WithHTTPClient(client *http.Client) *ImportNetworkLinkParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the import network link params
func (o *ImportNetworkLinkParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithImportParameters adds the importParameters to the import network link params
func (o *ImportNetworkLinkParams) WithImportParameters(importParameters ImportNetworkLinkBody) *ImportNetworkLinkParams {
	o.SetImportParameters(importParameters)
	return o
}

// SetImportParameters adds the importParameters to the import network link params
func (o *ImportNetworkLinkParams) SetImportParameters(importParameters ImportNetworkLinkBody) {
	o.ImportParameters = importParameters
}

// WriteToRequest writes these params to a swagger request
func (o *ImportNetworkLinkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.ImportParameters); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
