// Code generated by go-swagger; DO NOT EDIT.

package container

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// DetachContainerReader is a Reader for the DetachContainer structure.
type DetachContainerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DetachContainerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDetachContainerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDetachContainerDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDetachContainerOK creates a DetachContainerOK with default headers values
func NewDetachContainerOK() *DetachContainerOK {
	return &DetachContainerOK{}
}

/*DetachContainerOK handles this case with default header values.

Deleted a Container
*/
type DetachContainerOK struct {
}

func (o *DetachContainerOK) Error() string {
	return fmt.Sprintf("[DELETE /Deletes/detachContainer][%d] detachContainerOK ", 200)
}

func (o *DetachContainerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDetachContainerDefault creates a DetachContainerDefault with default headers values
func NewDetachContainerDefault(code int) *DetachContainerDefault {
	return &DetachContainerDefault{
		_statusCode: code,
	}
}

/*DetachContainerDefault handles this case with default header values.

Error response
*/
type DetachContainerDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the detach container default response
func (o *DetachContainerDefault) Code() int {
	return o._statusCode
}

func (o *DetachContainerDefault) Error() string {
	return fmt.Sprintf("[DELETE /Deletes/detachContainer][%d] detachContainer default  %+v", o._statusCode, o.Payload)
}

func (o *DetachContainerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DetachContainerBody detach container body
swagger:model DetachContainerBody
*/
type DetachContainerBody struct {

	// container
	Container string `json:"container,omitempty"`

	// v4 dhcp server
	V4DhcpServer string `json:"v4DhcpServer,omitempty"`

	// v6 dhcp server
	V6DhcpServer string `json:"v6DhcpServer,omitempty"`
}

// Validate validates this detach container body
func (o *DetachContainerBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DetachContainerBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DetachContainerBody) UnmarshalBinary(b []byte) error {
	var res DetachContainerBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
