// Code generated by go-swagger; DO NOT EDIT.

package container

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// GetContainerParentHierarchyReader is a Reader for the GetContainerParentHierarchy structure.
type GetContainerParentHierarchyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetContainerParentHierarchyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetContainerParentHierarchyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetContainerParentHierarchyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetContainerParentHierarchyOK creates a GetContainerParentHierarchyOK with default headers values
func NewGetContainerParentHierarchyOK() *GetContainerParentHierarchyOK {
	return &GetContainerParentHierarchyOK{}
}

/*GetContainerParentHierarchyOK handles this case with default header values.

ContainerParentHierarchy
*/
type GetContainerParentHierarchyOK struct {
	Payload []string
}

func (o *GetContainerParentHierarchyOK) Error() string {
	return fmt.Sprintf("[GET /Gets/getContainerParentHierarchy][%d] getContainerParentHierarchyOK  %+v", 200, o.Payload)
}

func (o *GetContainerParentHierarchyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetContainerParentHierarchyDefault creates a GetContainerParentHierarchyDefault with default headers values
func NewGetContainerParentHierarchyDefault(code int) *GetContainerParentHierarchyDefault {
	return &GetContainerParentHierarchyDefault{
		_statusCode: code,
	}
}

/*GetContainerParentHierarchyDefault handles this case with default header values.

Error response
*/
type GetContainerParentHierarchyDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the get container parent hierarchy default response
func (o *GetContainerParentHierarchyDefault) Code() int {
	return o._statusCode
}

func (o *GetContainerParentHierarchyDefault) Error() string {
	return fmt.Sprintf("[GET /Gets/getContainerParentHierarchy][%d] getContainerParentHierarchy default  %+v", o._statusCode, o.Payload)
}

func (o *GetContainerParentHierarchyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
