// Code generated by go-swagger; DO NOT EDIT.

package container

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// ImportContainerReader is a Reader for the ImportContainer structure.
type ImportContainerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ImportContainerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewImportContainerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewImportContainerDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewImportContainerOK creates a ImportContainerOK with default headers values
func NewImportContainerOK() *ImportContainerOK {
	return &ImportContainerOK{}
}

/*ImportContainerOK handles this case with default header values.

Imports of Container completed
*/
type ImportContainerOK struct {
}

func (o *ImportContainerOK) Error() string {
	return fmt.Sprintf("[POST /Imports/importContainer][%d] importContainerOK ", 200)
}

func (o *ImportContainerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewImportContainerDefault creates a ImportContainerDefault with default headers values
func NewImportContainerDefault(code int) *ImportContainerDefault {
	return &ImportContainerDefault{
		_statusCode: code,
	}
}

/*ImportContainerDefault handles this case with default header values.

Error response
*/
type ImportContainerDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the import container default response
func (o *ImportContainerDefault) Code() int {
	return o._statusCode
}

func (o *ImportContainerDefault) Error() string {
	return fmt.Sprintf("[POST /Imports/importContainer][%d] importContainer default  %+v", o._statusCode, o.Payload)
}

func (o *ImportContainerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ImportContainerBody import container body
swagger:model ImportContainerBody
*/
type ImportContainerBody struct {

	// inp container
	InpContainer *models.WSContainer `json:"inpContainer,omitempty"`
}

// Validate validates this import container body
func (o *ImportContainerBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateInpContainer(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ImportContainerBody) validateInpContainer(formats strfmt.Registry) error {

	if swag.IsZero(o.InpContainer) { // not required
		return nil
	}

	if o.InpContainer != nil {
		if err := o.InpContainer.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Import Parameters" + "." + "inpContainer")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ImportContainerBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ImportContainerBody) UnmarshalBinary(b []byte) error {
	var res ImportContainerBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
