// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Fault fault
// swagger:model Fault
type Fault struct {

	// fault detail
	FaultDetail int64 `json:"faultDetail,omitempty"`

	// fault string
	FaultString string `json:"faultString,omitempty"`
}

// Validate validates this fault
func (m *Fault) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Fault) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Fault) UnmarshalBinary(b []byte) error {
	var res Fault
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
