// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// WSDhcpPolicy w s dhcp policy
// swagger:model WSDhcpPolicy
type WSDhcpPolicy struct {

	// applies to
	AppliesTo string `json:"appliesTo,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// policy value
	PolicyValue string `json:"policyValue,omitempty"`
}

// Validate validates this w s dhcp policy
func (m *WSDhcpPolicy) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WSDhcpPolicy) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WSDhcpPolicy) UnmarshalBinary(b []byte) error {
	var res WSDhcpPolicy
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
