// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// WSIPAddressRange w s Ip address range
// swagger:model WSIpAddressRange
type WSIPAddressRange struct {

	// d h c p option set
	DHCPOptionSet string `json:"DHCPOptionSet,omitempty"`

	// d h c p policy set
	DHCPPolicySet string `json:"DHCPPolicySet,omitempty"`

	// address type
	AddressType string `json:"addressType,omitempty"`

	// container
	Container string `json:"container,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// device type
	DeviceType string `json:"deviceType,omitempty"`

	// domain name
	DomainName string `json:"domainName,omitempty"`

	// domain type
	DomainType string `json:"domainType,omitempty"`

	// dup warning
	DupWarning bool `json:"dupWarning,omitempty"`

	// end Ip address
	EndIPAddress string `json:"endIpAddress,omitempty"`

	// exclude from discovery
	ExcludeFromDiscovery bool `json:"excludeFromDiscovery,omitempty"`

	// failover d h c p server
	FailoverDHCPServer string `json:"failoverDHCPServer,omitempty"`

	// hostname template
	HostnameTemplate string `json:"hostnameTemplate,omitempty"`

	// primary d h c p server
	PrimaryDHCPServer string `json:"primaryDHCPServer,omitempty"`

	// range size
	RangeSize string `json:"rangeSize,omitempty"`

	// resource a record flag
	ResourceARecordFlag bool `json:"resourceARecordFlag,omitempty"`

	// resource p t r record flag
	ResourcePTRRecordFlag bool `json:"resourcePTRRecordFlag,omitempty"`

	// start Ip address
	StartIPAddress string `json:"startIpAddress,omitempty"`

	// user defined fields
	UserDefinedFields []string `json:"userDefinedFields"`
}

// Validate validates this w s Ip address range
func (m *WSIPAddressRange) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WSIPAddressRange) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WSIPAddressRange) UnmarshalBinary(b []byte) error {
	var res WSIPAddressRange
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
