// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// WSAdminOtherPolicies w s admin other policies
// swagger:model WSAdminOtherPolicies
type WSAdminOtherPolicies struct {

	// allow c l i access
	AllowCLIAccess bool `json:"allowCLIAccess,omitempty"`

	// allow dup a rec check
	AllowDupARecCheck string `json:"allowDupARecCheck,omitempty"`

	// allow dup hostname check
	AllowDupHostnameCheck string `json:"allowDupHostnameCheck,omitempty"`

	// allow dup hw addr check
	AllowDupHwAddrCheck string `json:"allowDupHwAddrCheck,omitempty"`

	// allow g UI access
	AllowGUIAccess bool `json:"allowGUIAccess,omitempty"`

	// dup hostname checking style
	DupHostnameCheckingStyle string `json:"dupHostnameCheckingStyle,omitempty"`
}

// Validate validates this w s admin other policies
func (m *WSAdminOtherPolicies) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WSAdminOtherPolicies) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WSAdminOtherPolicies) UnmarshalBinary(b []byte) error {
	var res WSAdminOtherPolicies
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
