// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// WSChildBlock w s child block
// swagger:model WSChildBlock
type WSChildBlock struct {

	// s w ipname
	SWIpname string `json:"SWIPname,omitempty"`

	// allocation reason
	AllocationReason string `json:"allocationReason,omitempty"`

	// allocation reason description
	AllocationReasonDescription string `json:"allocationReasonDescription,omitempty"`

	// allocation strategy
	AllocationStrategy string `json:"allocationStrategy,omitempty"`

	// allocation template
	AllocationTemplate string `json:"allocationTemplate,omitempty"`

	// block addr
	BlockAddr string `json:"blockAddr,omitempty"`

	// block name
	BlockName string `json:"blockName,omitempty"`

	// block size
	BlockSize string `json:"blockSize,omitempty"`

	// block status
	BlockStatus string `json:"blockStatus,omitempty"`

	// block type
	BlockType string `json:"blockType,omitempty"`

	// cloud object Id
	CloudObjectID string `json:"cloudObjectId,omitempty"`

	// cloud type
	CloudType string `json:"cloudType,omitempty"`

	// container
	Container string `json:"container,omitempty"`

	// create date
	CreateDate string `json:"createDate,omitempty"`

	// create reverse domains
	CreateReverseDomains string `json:"createReverseDomains,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// discovery agent
	DiscoveryAgent string `json:"discoveryAgent,omitempty"`

	// domain type
	DomainType string `json:"domainType,omitempty"`

	// exclude from discovery
	ExcludeFromDiscovery string `json:"excludeFromDiscovery,omitempty"`

	// interface address
	InterfaceAddress []string `json:"interfaceAddress"`

	// interface name
	InterfaceName string `json:"interfaceName,omitempty"`

	// ipv6
	IPV6 bool `json:"ipv6,omitempty"`

	// last update date
	LastUpdateDate string `json:"lastUpdateDate,omitempty"`

	// non broadcast
	NonBroadcast bool `json:"nonBroadcast,omitempty"`

	// primary subnet
	PrimarySubnet bool `json:"primarySubnet,omitempty"`

	// user defined fields
	UserDefinedFields []string `json:"userDefinedFields"`

	// vrf name
	VrfName string `json:"vrfName,omitempty"`
}

// Validate validates this w s child block
func (m *WSChildBlock) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WSChildBlock) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WSChildBlock) UnmarshalBinary(b []byte) error {
	var res WSChildBlock
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
