// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// WSSite w s site
// swagger:model WSSite
type WSSite struct {

	// container
	Container string `json:"container,omitempty"`

	// site block details
	SiteBlockDetails []*WSSiteBlockDetails `json:"siteBlockDetails"`

	// site template name
	SiteTemplateName string `json:"siteTemplateName,omitempty"`
}

// Validate validates this w s site
func (m *WSSite) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSiteBlockDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WSSite) validateSiteBlockDetails(formats strfmt.Registry) error {

	if swag.IsZero(m.SiteBlockDetails) { // not required
		return nil
	}

	for i := 0; i < len(m.SiteBlockDetails); i++ {
		if swag.IsZero(m.SiteBlockDetails[i]) { // not required
			continue
		}

		if m.SiteBlockDetails[i] != nil {
			if err := m.SiteBlockDetails[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("siteBlockDetails" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *WSSite) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WSSite) UnmarshalBinary(b []byte) error {
	var res WSSite
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
