// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// WSBlockACLInfo w s block ACL info
// swagger:model WSBlockACLInfo
type WSBlockACLInfo struct {

	// allow delete
	AllowDelete bool `json:"allowDelete,omitempty"`

	// allow read
	AllowRead bool `json:"allowRead,omitempty"`

	// allow write
	AllowWrite bool `json:"allowWrite,omitempty"`

	// block name
	BlockName string `json:"blockName,omitempty"`

	// block status
	BlockStatus string `json:"blockStatus,omitempty"`

	// container name
	ContainerName string `json:"containerName,omitempty"`

	// device approve access
	DeviceApproveAccess bool `json:"deviceApproveAccess,omitempty"`
}

// Validate validates this w s block ACL info
func (m *WSBlockACLInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WSBlockACLInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WSBlockACLInfo) UnmarshalBinary(b []byte) error {
	var res WSBlockACLInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
