// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// WSBlockTypeSizeACL w s block type size ACL
// swagger:model WSBlockTypeSizeACL
type WSBlockTypeSizeACL struct {

	// block type
	BlockType string `json:"blockType,omitempty"`

	// v4 abstain
	V4Abstain bool `json:"v4Abstain,omitempty"`

	// v4 block size
	V4BlockSize []int64 `json:"v4BlockSize"`

	// v6 abstain
	V6Abstain bool `json:"v6Abstain,omitempty"`

	// v6 block size
	V6BlockSize []int64 `json:"v6BlockSize"`
}

// Validate validates this w s block type size ACL
func (m *WSBlockTypeSizeACL) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WSBlockTypeSizeACL) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WSBlockTypeSizeACL) UnmarshalBinary(b []byte) error {
	var res WSBlockTypeSizeACL
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
