// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// WSRootBlock w s root block
// swagger:model WSRootBlock
type WSRootBlock struct {

	// r i r
	RIR string `json:"RIR,omitempty"`

	// s w ipname
	SWIpname string `json:"SWIPname,omitempty"`

	// allocation reason
	AllocationReason string `json:"allocationReason,omitempty"`

	// allocation reason description
	AllocationReasonDescription string `json:"allocationReasonDescription,omitempty"`

	// allow overlapping space
	AllowOverlappingSpace string `json:"allowOverlappingSpace,omitempty"`

	// block addr
	BlockAddr string `json:"blockAddr,omitempty"`

	// block name
	BlockName string `json:"blockName,omitempty"`

	// block size
	BlockSize string `json:"blockSize,omitempty"`

	// block type
	BlockType string `json:"blockType,omitempty"`

	// cloud object Id
	CloudObjectID string `json:"cloudObjectId,omitempty"`

	// cloud type
	CloudType string `json:"cloudType,omitempty"`

	// container
	Container string `json:"container,omitempty"`

	// create reverse domains
	CreateReverseDomains string `json:"createReverseDomains,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// domain type
	DomainType string `json:"domainType,omitempty"`

	// organization Id
	OrganizationID string `json:"organizationId,omitempty"`

	// user defined fields
	UserDefinedFields []string `json:"userDefinedFields"`
}

// Validate validates this w s root block
func (m *WSRootBlock) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WSRootBlock) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WSRootBlock) UnmarshalBinary(b []byte) error {
	var res WSRootBlock
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
