// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// WSContainerACLInfo w s container ACL info
// swagger:model WSContainerACLInfo
type WSContainerACLInfo struct {

	// allow delete
	AllowDelete bool `json:"allowDelete,omitempty"`

	// allow read
	AllowRead bool `json:"allowRead,omitempty"`

	// allow write
	AllowWrite bool `json:"allowWrite,omitempty"`

	// apply to children
	ApplyToChildren bool `json:"applyToChildren,omitempty"`

	// container name
	ContainerName string `json:"containerName,omitempty"`

	// device approve access
	DeviceApproveAccess bool `json:"deviceApproveAccess,omitempty"`
}

// Validate validates this w s container ACL info
func (m *WSContainerACLInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WSContainerACLInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WSContainerACLInfo) UnmarshalBinary(b []byte) error {
	var res WSContainerACLInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
