// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// WSChildSubnetBlock w s child subnet block
// swagger:model WSChildSubnetBlock
type WSChildSubnetBlock struct {

	// child block
	ChildBlock *WSChildBlock `json:"childBlock,omitempty"`

	// subnet policy
	SubnetPolicy *WSSubnetPolicy `json:"subnetPolicy,omitempty"`
}

// Validate validates this w s child subnet block
func (m *WSChildSubnetBlock) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChildBlock(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSubnetPolicy(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WSChildSubnetBlock) validateChildBlock(formats strfmt.Registry) error {

	if swag.IsZero(m.ChildBlock) { // not required
		return nil
	}

	if m.ChildBlock != nil {
		if err := m.ChildBlock.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("childBlock")
			}
			return err
		}
	}

	return nil
}

func (m *WSChildSubnetBlock) validateSubnetPolicy(formats strfmt.Registry) error {

	if swag.IsZero(m.SubnetPolicy) { // not required
		return nil
	}

	if m.SubnetPolicy != nil {
		if err := m.SubnetPolicy.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("subnetPolicy")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *WSChildSubnetBlock) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WSChildSubnetBlock) UnmarshalBinary(b []byte) error {
	var res WSChildSubnetBlock
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
