// Code generated by go-swagger; DO NOT EDIT.

package prefix_pool

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// GetPrefixPoolByStartAddrReader is a Reader for the GetPrefixPoolByStartAddr structure.
type GetPrefixPoolByStartAddrReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPrefixPoolByStartAddrReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPrefixPoolByStartAddrOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetPrefixPoolByStartAddrDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetPrefixPoolByStartAddrOK creates a GetPrefixPoolByStartAddrOK with default headers values
func NewGetPrefixPoolByStartAddrOK() *GetPrefixPoolByStartAddrOK {
	return &GetPrefixPoolByStartAddrOK{}
}

/*GetPrefixPoolByStartAddrOK handles this case with default header values.

PrefixPool
*/
type GetPrefixPoolByStartAddrOK struct {
	Payload *models.WSPrefixPool
}

func (o *GetPrefixPoolByStartAddrOK) Error() string {
	return fmt.Sprintf("[GET /Gets/getPrefixPoolByStartAddr][%d] getPrefixPoolByStartAddrOK  %+v", 200, o.Payload)
}

func (o *GetPrefixPoolByStartAddrOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WSPrefixPool)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPrefixPoolByStartAddrDefault creates a GetPrefixPoolByStartAddrDefault with default headers values
func NewGetPrefixPoolByStartAddrDefault(code int) *GetPrefixPoolByStartAddrDefault {
	return &GetPrefixPoolByStartAddrDefault{
		_statusCode: code,
	}
}

/*GetPrefixPoolByStartAddrDefault handles this case with default header values.

Error response
*/
type GetPrefixPoolByStartAddrDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the get prefix pool by start addr default response
func (o *GetPrefixPoolByStartAddrDefault) Code() int {
	return o._statusCode
}

func (o *GetPrefixPoolByStartAddrDefault) Error() string {
	return fmt.Sprintf("[GET /Gets/getPrefixPoolByStartAddr][%d] getPrefixPoolByStartAddr default  %+v", o._statusCode, o.Payload)
}

func (o *GetPrefixPoolByStartAddrDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
