// Code generated by go-swagger; DO NOT EDIT.

package prefix_pool

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// InitExportPrefixPoolReader is a Reader for the InitExportPrefixPool structure.
type InitExportPrefixPoolReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InitExportPrefixPoolReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewInitExportPrefixPoolOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewInitExportPrefixPoolDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewInitExportPrefixPoolOK creates a InitExportPrefixPoolOK with default headers values
func NewInitExportPrefixPoolOK() *InitExportPrefixPoolOK {
	return &InitExportPrefixPoolOK{}
}

/*InitExportPrefixPoolOK handles this case with default header values.

Exports of PrefixPool initialized
*/
type InitExportPrefixPoolOK struct {
	Payload *models.WSContext
}

func (o *InitExportPrefixPoolOK) Error() string {
	return fmt.Sprintf("[POST /Exports/initExportPrefixPool][%d] initExportPrefixPoolOK  %+v", 200, o.Payload)
}

func (o *InitExportPrefixPoolOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WSContext)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewInitExportPrefixPoolDefault creates a InitExportPrefixPoolDefault with default headers values
func NewInitExportPrefixPoolDefault(code int) *InitExportPrefixPoolDefault {
	return &InitExportPrefixPoolDefault{
		_statusCode: code,
	}
}

/*InitExportPrefixPoolDefault handles this case with default header values.

Error response
*/
type InitExportPrefixPoolDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the init export prefix pool default response
func (o *InitExportPrefixPoolDefault) Code() int {
	return o._statusCode
}

func (o *InitExportPrefixPoolDefault) Error() string {
	return fmt.Sprintf("[POST /Exports/initExportPrefixPool][%d] initExportPrefixPool default  %+v", o._statusCode, o.Payload)
}

func (o *InitExportPrefixPoolDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*InitExportPrefixPoolBody init export prefix pool body
swagger:model InitExportPrefixPoolBody
*/
type InitExportPrefixPoolBody struct {

	// filter
	Filter string `json:"filter,omitempty"`

	// first result pos
	FirstResultPos int64 `json:"firstResultPos,omitempty"`

	// options
	Options []string `json:"options"`

	// page size
	PageSize int64 `json:"pageSize,omitempty"`
}

// Validate validates this init export prefix pool body
func (o *InitExportPrefixPoolBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *InitExportPrefixPoolBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *InitExportPrefixPoolBody) UnmarshalBinary(b []byte) error {
	var res InitExportPrefixPoolBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
