// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// DhcpConfigurationAllFilesReader is a Reader for the DhcpConfigurationAllFiles structure.
type DhcpConfigurationAllFilesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DhcpConfigurationAllFilesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDhcpConfigurationAllFilesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDhcpConfigurationAllFilesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDhcpConfigurationAllFilesOK creates a DhcpConfigurationAllFilesOK with default headers values
func NewDhcpConfigurationAllFilesOK() *DhcpConfigurationAllFilesOK {
	return &DhcpConfigurationAllFilesOK{}
}

/*DhcpConfigurationAllFilesOK handles this case with default header values.

integer returned
*/
type DhcpConfigurationAllFilesOK struct {
	Payload *DhcpConfigurationAllFilesOKBody
}

func (o *DhcpConfigurationAllFilesOK) Error() string {
	return fmt.Sprintf("[POST /TaskInvocation/dhcpConfigurationAllFiles][%d] dhcpConfigurationAllFilesOK  %+v", 200, o.Payload)
}

func (o *DhcpConfigurationAllFilesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DhcpConfigurationAllFilesOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDhcpConfigurationAllFilesDefault creates a DhcpConfigurationAllFilesDefault with default headers values
func NewDhcpConfigurationAllFilesDefault(code int) *DhcpConfigurationAllFilesDefault {
	return &DhcpConfigurationAllFilesDefault{
		_statusCode: code,
	}
}

/*DhcpConfigurationAllFilesDefault handles this case with default header values.

Error response
*/
type DhcpConfigurationAllFilesDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the dhcp configuration all files default response
func (o *DhcpConfigurationAllFilesDefault) Code() int {
	return o._statusCode
}

func (o *DhcpConfigurationAllFilesDefault) Error() string {
	return fmt.Sprintf("[POST /TaskInvocation/dhcpConfigurationAllFiles][%d] dhcpConfigurationAllFiles default  %+v", o._statusCode, o.Payload)
}

func (o *DhcpConfigurationAllFilesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DhcpConfigurationAllFilesBody dhcp configuration all files body
swagger:model DhcpConfigurationAllFilesBody
*/
type DhcpConfigurationAllFilesBody struct {

	// create diff
	CreateDiff bool `json:"createDiff,omitempty"`

	// ignore ddns errors
	IgnoreDdnsErrors bool `json:"ignoreDdnsErrors,omitempty"`

	// ip
	IP string `json:"ip,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// priority
	Priority bool `json:"priority,omitempty"`

	// push only changes
	PushOnlyChanges bool `json:"pushOnlyChanges,omitempty"`

	// stop on error
	StopOnError bool `json:"stopOnError,omitempty"`

	// update failovers
	UpdateFailovers bool `json:"updateFailovers,omitempty"`
}

// Validate validates this dhcp configuration all files body
func (o *DhcpConfigurationAllFilesBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DhcpConfigurationAllFilesBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DhcpConfigurationAllFilesBody) UnmarshalBinary(b []byte) error {
	var res DhcpConfigurationAllFilesBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DhcpConfigurationAllFilesOKBody dhcp configuration all files o k body
swagger:model DhcpConfigurationAllFilesOKBody
*/
type DhcpConfigurationAllFilesOKBody struct {

	// result
	Result int64 `json:"result,omitempty"`
}

// Validate validates this dhcp configuration all files o k body
func (o *DhcpConfigurationAllFilesOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DhcpConfigurationAllFilesOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DhcpConfigurationAllFilesOKBody) UnmarshalBinary(b []byte) error {
	var res DhcpConfigurationAllFilesOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
