// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// DiscoverSubnetHostsReader is a Reader for the DiscoverSubnetHosts structure.
type DiscoverSubnetHostsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DiscoverSubnetHostsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDiscoverSubnetHostsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDiscoverSubnetHostsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDiscoverSubnetHostsOK creates a DiscoverSubnetHostsOK with default headers values
func NewDiscoverSubnetHostsOK() *DiscoverSubnetHostsOK {
	return &DiscoverSubnetHostsOK{}
}

/*DiscoverSubnetHostsOK handles this case with default header values.

integer returned
*/
type DiscoverSubnetHostsOK struct {
	Payload *DiscoverSubnetHostsOKBody
}

func (o *DiscoverSubnetHostsOK) Error() string {
	return fmt.Sprintf("[POST /TaskInvocation/discoverSubnetHosts][%d] discoverSubnetHostsOK  %+v", 200, o.Payload)
}

func (o *DiscoverSubnetHostsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DiscoverSubnetHostsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDiscoverSubnetHostsDefault creates a DiscoverSubnetHostsDefault with default headers values
func NewDiscoverSubnetHostsDefault(code int) *DiscoverSubnetHostsDefault {
	return &DiscoverSubnetHostsDefault{
		_statusCode: code,
	}
}

/*DiscoverSubnetHostsDefault handles this case with default header values.

Error response
*/
type DiscoverSubnetHostsDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the discover subnet hosts default response
func (o *DiscoverSubnetHostsDefault) Code() int {
	return o._statusCode
}

func (o *DiscoverSubnetHostsDefault) Error() string {
	return fmt.Sprintf("[POST /TaskInvocation/discoverSubnetHosts][%d] discoverSubnetHosts default  %+v", o._statusCode, o.Payload)
}

func (o *DiscoverSubnetHostsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DiscoverSubnetHostsBody discover subnet hosts body
swagger:model DiscoverSubnetHostsBody
*/
type DiscoverSubnetHostsBody struct {

	// container
	Container string `json:"container,omitempty"`

	// ignore duplicates
	IgnoreDuplicates bool `json:"ignoreDuplicates,omitempty"`

	// lookup hostname
	LookupHostname bool `json:"lookupHostname,omitempty"`

	// perform net host add
	PerformNetHostAdd bool `json:"performNetHostAdd,omitempty"`

	// perform net r r add
	PerformNetRRAdd bool `json:"performNetRRAdd,omitempty"`

	// ping hosts
	PingHosts string `json:"pingHosts,omitempty"`

	// priority
	Priority bool `json:"priority,omitempty"`

	// subnet address
	SubnetAddress string `json:"subnetAddress,omitempty"`
}

// Validate validates this discover subnet hosts body
func (o *DiscoverSubnetHostsBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DiscoverSubnetHostsBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DiscoverSubnetHostsBody) UnmarshalBinary(b []byte) error {
	var res DiscoverSubnetHostsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DiscoverSubnetHostsOKBody discover subnet hosts o k body
swagger:model DiscoverSubnetHostsOKBody
*/
type DiscoverSubnetHostsOKBody struct {

	// result
	Result int64 `json:"result,omitempty"`
}

// Validate validates this discover subnet hosts o k body
func (o *DiscoverSubnetHostsOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DiscoverSubnetHostsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DiscoverSubnetHostsOKBody) UnmarshalBinary(b []byte) error {
	var res DiscoverSubnetHostsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
