// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// DNSDDNSChangedRRsReader is a Reader for the DNSDDNSChangedRRs structure.
type DNSDDNSChangedRRsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DNSDDNSChangedRRsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDNSDDNSChangedRRsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDNSDDNSChangedRRsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDNSDDNSChangedRRsOK creates a DNSDDNSChangedRRsOK with default headers values
func NewDNSDDNSChangedRRsOK() *DNSDDNSChangedRRsOK {
	return &DNSDDNSChangedRRsOK{}
}

/*DNSDDNSChangedRRsOK handles this case with default header values.

integer returned
*/
type DNSDDNSChangedRRsOK struct {
	Payload *DNSDDNSChangedRRsOKBody
}

func (o *DNSDDNSChangedRRsOK) Error() string {
	return fmt.Sprintf("[POST /TaskInvocation/dnsDDNSChangedRRs][%d] dnsDDnsChangedRRsOK  %+v", 200, o.Payload)
}

func (o *DNSDDNSChangedRRsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DNSDDNSChangedRRsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDNSDDNSChangedRRsDefault creates a DNSDDNSChangedRRsDefault with default headers values
func NewDNSDDNSChangedRRsDefault(code int) *DNSDDNSChangedRRsDefault {
	return &DNSDDNSChangedRRsDefault{
		_statusCode: code,
	}
}

/*DNSDDNSChangedRRsDefault handles this case with default header values.

Error response
*/
type DNSDDNSChangedRRsDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the dns d DNS changed r rs default response
func (o *DNSDDNSChangedRRsDefault) Code() int {
	return o._statusCode
}

func (o *DNSDDNSChangedRRsDefault) Error() string {
	return fmt.Sprintf("[POST /TaskInvocation/dnsDDNSChangedRRs][%d] dnsDDNSChangedRRs default  %+v", o._statusCode, o.Payload)
}

func (o *DNSDDNSChangedRRsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DNSDDNSChangedRRsBody DNS d DNS changed r rs body
swagger:model DNSDDNSChangedRRsBody
*/
type DNSDDNSChangedRRsBody struct {

	// ip
	IP string `json:"ip,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// priority
	Priority bool `json:"priority,omitempty"`
}

// Validate validates this DNS d DNS changed r rs body
func (o *DNSDDNSChangedRRsBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DNSDDNSChangedRRsBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DNSDDNSChangedRRsBody) UnmarshalBinary(b []byte) error {
	var res DNSDDNSChangedRRsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DNSDDNSChangedRRsOKBody DNS d DNS changed r rs o k body
swagger:model DNSDDNSChangedRRsOKBody
*/
type DNSDDNSChangedRRsOKBody struct {

	// result
	Result int64 `json:"result,omitempty"`
}

// Validate validates this DNS d DNS changed r rs o k body
func (o *DNSDDNSChangedRRsOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DNSDDNSChangedRRsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DNSDDNSChangedRRsOKBody) UnmarshalBinary(b []byte) error {
	var res DNSDDNSChangedRRsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
