// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// DomainControllerConfigurationReader is a Reader for the DomainControllerConfiguration structure.
type DomainControllerConfigurationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DomainControllerConfigurationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDomainControllerConfigurationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDomainControllerConfigurationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDomainControllerConfigurationOK creates a DomainControllerConfigurationOK with default headers values
func NewDomainControllerConfigurationOK() *DomainControllerConfigurationOK {
	return &DomainControllerConfigurationOK{}
}

/*DomainControllerConfigurationOK handles this case with default header values.

integer returned
*/
type DomainControllerConfigurationOK struct {
	Payload *DomainControllerConfigurationOKBody
}

func (o *DomainControllerConfigurationOK) Error() string {
	return fmt.Sprintf("[POST /TaskInvocation/domainControllerConfiguration][%d] domainControllerConfigurationOK  %+v", 200, o.Payload)
}

func (o *DomainControllerConfigurationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DomainControllerConfigurationOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDomainControllerConfigurationDefault creates a DomainControllerConfigurationDefault with default headers values
func NewDomainControllerConfigurationDefault(code int) *DomainControllerConfigurationDefault {
	return &DomainControllerConfigurationDefault{
		_statusCode: code,
	}
}

/*DomainControllerConfigurationDefault handles this case with default header values.

Error response
*/
type DomainControllerConfigurationDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the domain controller configuration default response
func (o *DomainControllerConfigurationDefault) Code() int {
	return o._statusCode
}

func (o *DomainControllerConfigurationDefault) Error() string {
	return fmt.Sprintf("[POST /TaskInvocation/domainControllerConfiguration][%d] domainControllerConfiguration default  %+v", o._statusCode, o.Payload)
}

func (o *DomainControllerConfigurationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DomainControllerConfigurationBody domain controller configuration body
swagger:model DomainControllerConfigurationBody
*/
type DomainControllerConfigurationBody struct {

	// dc name
	DcName string `json:"dcName,omitempty"`

	// ip address
	IPAddress string `json:"ipAddress,omitempty"`

	// preview
	Preview bool `json:"preview,omitempty"`

	// priority
	Priority bool `json:"priority,omitempty"`
}

// Validate validates this domain controller configuration body
func (o *DomainControllerConfigurationBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DomainControllerConfigurationBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DomainControllerConfigurationBody) UnmarshalBinary(b []byte) error {
	var res DomainControllerConfigurationBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DomainControllerConfigurationOKBody domain controller configuration o k body
swagger:model DomainControllerConfigurationOKBody
*/
type DomainControllerConfigurationOKBody struct {

	// result
	Result int64 `json:"result,omitempty"`
}

// Validate validates this domain controller configuration o k body
func (o *DomainControllerConfigurationOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DomainControllerConfigurationOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DomainControllerConfigurationOKBody) UnmarshalBinary(b []byte) error {
	var res DomainControllerConfigurationOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
