// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// GlobalNetServiceSyncReader is a Reader for the GlobalNetServiceSync structure.
type GlobalNetServiceSyncReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GlobalNetServiceSyncReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGlobalNetServiceSyncOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGlobalNetServiceSyncDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGlobalNetServiceSyncOK creates a GlobalNetServiceSyncOK with default headers values
func NewGlobalNetServiceSyncOK() *GlobalNetServiceSyncOK {
	return &GlobalNetServiceSyncOK{}
}

/*GlobalNetServiceSyncOK handles this case with default header values.

integer returned
*/
type GlobalNetServiceSyncOK struct {
	Payload *GlobalNetServiceSyncOKBody
}

func (o *GlobalNetServiceSyncOK) Error() string {
	return fmt.Sprintf("[POST /TaskInvocation/globalNetServiceSync][%d] globalNetServiceSyncOK  %+v", 200, o.Payload)
}

func (o *GlobalNetServiceSyncOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GlobalNetServiceSyncOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGlobalNetServiceSyncDefault creates a GlobalNetServiceSyncDefault with default headers values
func NewGlobalNetServiceSyncDefault(code int) *GlobalNetServiceSyncDefault {
	return &GlobalNetServiceSyncDefault{
		_statusCode: code,
	}
}

/*GlobalNetServiceSyncDefault handles this case with default header values.

Error response
*/
type GlobalNetServiceSyncDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the global net service sync default response
func (o *GlobalNetServiceSyncDefault) Code() int {
	return o._statusCode
}

func (o *GlobalNetServiceSyncDefault) Error() string {
	return fmt.Sprintf("[POST /TaskInvocation/globalNetServiceSync][%d] globalNetServiceSync default  %+v", o._statusCode, o.Payload)
}

func (o *GlobalNetServiceSyncDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GlobalNetServiceSyncBody global net service sync body
swagger:model GlobalNetServiceSyncBody
*/
type GlobalNetServiceSyncBody struct {

	// priority
	Priority bool `json:"priority,omitempty"`
}

// Validate validates this global net service sync body
func (o *GlobalNetServiceSyncBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GlobalNetServiceSyncBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GlobalNetServiceSyncBody) UnmarshalBinary(b []byte) error {
	var res GlobalNetServiceSyncBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GlobalNetServiceSyncOKBody global net service sync o k body
swagger:model GlobalNetServiceSyncOKBody
*/
type GlobalNetServiceSyncOKBody struct {

	// result
	Result int64 `json:"result,omitempty"`
}

// Validate validates this global net service sync o k body
func (o *GlobalNetServiceSyncOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GlobalNetServiceSyncOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GlobalNetServiceSyncOKBody) UnmarshalBinary(b []byte) error {
	var res GlobalNetServiceSyncOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
