// Code generated by go-swagger; DO NOT EDIT.

package administrator

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewImportAdminParams creates a new ImportAdminParams object
// with the default values initialized.
func NewImportAdminParams() *ImportAdminParams {
	var ()
	return &ImportAdminParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewImportAdminParamsWithTimeout creates a new ImportAdminParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewImportAdminParamsWithTimeout(timeout time.Duration) *ImportAdminParams {
	var ()
	return &ImportAdminParams{

		timeout: timeout,
	}
}

// NewImportAdminParamsWithContext creates a new ImportAdminParams object
// with the default values initialized, and the ability to set a context for a request
func NewImportAdminParamsWithContext(ctx context.Context) *ImportAdminParams {
	var ()
	return &ImportAdminParams{

		Context: ctx,
	}
}

// NewImportAdminParamsWithHTTPClient creates a new ImportAdminParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewImportAdminParamsWithHTTPClient(client *http.Client) *ImportAdminParams {
	var ()
	return &ImportAdminParams{
		HTTPClient: client,
	}
}

/*ImportAdminParams contains all the parameters to send to the API endpoint
for the import admin operation typically these are written to a http.Request
*/
type ImportAdminParams struct {

	/*ImportParameters
	  The input describing the administrator. loginId and password are required

	*/
	ImportParameters ImportAdminBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the import admin params
func (o *ImportAdminParams) WithTimeout(timeout time.Duration) *ImportAdminParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the import admin params
func (o *ImportAdminParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the import admin params
func (o *ImportAdminParams) WithContext(ctx context.Context) *ImportAdminParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the import admin params
func (o *ImportAdminParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the import admin params
func (o *ImportAdminParams) WithHTTPClient(client *http.Client) *ImportAdminParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the import admin params
func (o *ImportAdminParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithImportParameters adds the importParameters to the import admin params
func (o *ImportAdminParams) WithImportParameters(importParameters ImportAdminBody) *ImportAdminParams {
	o.SetImportParameters(importParameters)
	return o
}

// SetImportParameters adds the importParameters to the import admin params
func (o *ImportAdminParams) SetImportParameters(importParameters ImportAdminBody) {
	o.ImportParameters = importParameters
}

// WriteToRequest writes these params to a swagger request
func (o *ImportAdminParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.ImportParameters); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
