// Code generated by go-swagger; DO NOT EDIT.

package d_h_c_p_policy_set

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// DeleteDhcpPolicySetReader is a Reader for the DeleteDhcpPolicySet structure.
type DeleteDhcpPolicySetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDhcpPolicySetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteDhcpPolicySetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDeleteDhcpPolicySetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteDhcpPolicySetOK creates a DeleteDhcpPolicySetOK with default headers values
func NewDeleteDhcpPolicySetOK() *DeleteDhcpPolicySetOK {
	return &DeleteDhcpPolicySetOK{}
}

/*DeleteDhcpPolicySetOK handles this case with default header values.

Deleted a DhcpPolicySet
*/
type DeleteDhcpPolicySetOK struct {
}

func (o *DeleteDhcpPolicySetOK) Error() string {
	return fmt.Sprintf("[DELETE /Deletes/deleteDhcpPolicySet][%d] deleteDhcpPolicySetOK ", 200)
}

func (o *DeleteDhcpPolicySetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDhcpPolicySetDefault creates a DeleteDhcpPolicySetDefault with default headers values
func NewDeleteDhcpPolicySetDefault(code int) *DeleteDhcpPolicySetDefault {
	return &DeleteDhcpPolicySetDefault{
		_statusCode: code,
	}
}

/*DeleteDhcpPolicySetDefault handles this case with default header values.

Error response
*/
type DeleteDhcpPolicySetDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the delete dhcp policy set default response
func (o *DeleteDhcpPolicySetDefault) Code() int {
	return o._statusCode
}

func (o *DeleteDhcpPolicySetDefault) Error() string {
	return fmt.Sprintf("[DELETE /Deletes/deleteDhcpPolicySet][%d] deleteDhcpPolicySet default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteDhcpPolicySetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DeleteDhcpPolicySetBody delete dhcp policy set body
swagger:model DeleteDhcpPolicySetBody
*/
type DeleteDhcpPolicySetBody struct {

	// inp policy set
	InpPolicySet *models.WSDhcpPolicySet `json:"inpPolicySet,omitempty"`
}

// Validate validates this delete dhcp policy set body
func (o *DeleteDhcpPolicySetBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateInpPolicySet(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteDhcpPolicySetBody) validateInpPolicySet(formats strfmt.Registry) error {

	if swag.IsZero(o.InpPolicySet) { // not required
		return nil
	}

	if o.InpPolicySet != nil {
		if err := o.InpPolicySet.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Delete Parameters" + "." + "inpPolicySet")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteDhcpPolicySetBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteDhcpPolicySetBody) UnmarshalBinary(b []byte) error {
	var res DeleteDhcpPolicySetBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
