// Code generated by go-swagger; DO NOT EDIT.

package d_h_c_p_policy_set

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewExportDhcpPolicySetParams creates a new ExportDhcpPolicySetParams object
// with the default values initialized.
func NewExportDhcpPolicySetParams() *ExportDhcpPolicySetParams {
	var ()
	return &ExportDhcpPolicySetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewExportDhcpPolicySetParamsWithTimeout creates a new ExportDhcpPolicySetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewExportDhcpPolicySetParamsWithTimeout(timeout time.Duration) *ExportDhcpPolicySetParams {
	var ()
	return &ExportDhcpPolicySetParams{

		timeout: timeout,
	}
}

// NewExportDhcpPolicySetParamsWithContext creates a new ExportDhcpPolicySetParams object
// with the default values initialized, and the ability to set a context for a request
func NewExportDhcpPolicySetParamsWithContext(ctx context.Context) *ExportDhcpPolicySetParams {
	var ()
	return &ExportDhcpPolicySetParams{

		Context: ctx,
	}
}

// NewExportDhcpPolicySetParamsWithHTTPClient creates a new ExportDhcpPolicySetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewExportDhcpPolicySetParamsWithHTTPClient(client *http.Client) *ExportDhcpPolicySetParams {
	var ()
	return &ExportDhcpPolicySetParams{
		HTTPClient: client,
	}
}

/*ExportDhcpPolicySetParams contains all the parameters to send to the API endpoint
for the export dhcp policy set operation typically these are written to a http.Request
*/
type ExportDhcpPolicySetParams struct {

	/*Wscontext
	  The results from an initExportDhcpPolicySet operation

	*/
	Wscontext ExportDhcpPolicySetBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the export dhcp policy set params
func (o *ExportDhcpPolicySetParams) WithTimeout(timeout time.Duration) *ExportDhcpPolicySetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the export dhcp policy set params
func (o *ExportDhcpPolicySetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the export dhcp policy set params
func (o *ExportDhcpPolicySetParams) WithContext(ctx context.Context) *ExportDhcpPolicySetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the export dhcp policy set params
func (o *ExportDhcpPolicySetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the export dhcp policy set params
func (o *ExportDhcpPolicySetParams) WithHTTPClient(client *http.Client) *ExportDhcpPolicySetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the export dhcp policy set params
func (o *ExportDhcpPolicySetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWscontext adds the wscontext to the export dhcp policy set params
func (o *ExportDhcpPolicySetParams) WithWscontext(wscontext ExportDhcpPolicySetBody) *ExportDhcpPolicySetParams {
	o.SetWscontext(wscontext)
	return o
}

// SetWscontext adds the wscontext to the export dhcp policy set params
func (o *ExportDhcpPolicySetParams) SetWscontext(wscontext ExportDhcpPolicySetBody) {
	o.Wscontext = wscontext
}

// WriteToRequest writes these params to a swagger request
func (o *ExportDhcpPolicySetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Wscontext); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
