// Code generated by go-swagger; DO NOT EDIT.

package d_h_c_p_policy_set

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// ExportDhcpPolicySetReader is a Reader for the ExportDhcpPolicySet structure.
type ExportDhcpPolicySetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExportDhcpPolicySetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewExportDhcpPolicySetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewExportDhcpPolicySetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewExportDhcpPolicySetOK creates a ExportDhcpPolicySetOK with default headers values
func NewExportDhcpPolicySetOK() *ExportDhcpPolicySetOK {
	return &ExportDhcpPolicySetOK{}
}

/*ExportDhcpPolicySetOK handles this case with default header values.

DhcpPolicySet returned
*/
type ExportDhcpPolicySetOK struct {
	Payload []*models.WSDhcpPolicySet
}

func (o *ExportDhcpPolicySetOK) Error() string {
	return fmt.Sprintf("[POST /Exports/exportDhcpPolicySet][%d] exportDhcpPolicySetOK  %+v", 200, o.Payload)
}

func (o *ExportDhcpPolicySetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExportDhcpPolicySetDefault creates a ExportDhcpPolicySetDefault with default headers values
func NewExportDhcpPolicySetDefault(code int) *ExportDhcpPolicySetDefault {
	return &ExportDhcpPolicySetDefault{
		_statusCode: code,
	}
}

/*ExportDhcpPolicySetDefault handles this case with default header values.

Error response
*/
type ExportDhcpPolicySetDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the export dhcp policy set default response
func (o *ExportDhcpPolicySetDefault) Code() int {
	return o._statusCode
}

func (o *ExportDhcpPolicySetDefault) Error() string {
	return fmt.Sprintf("[POST /Exports/exportDhcpPolicySet][%d] exportDhcpPolicySet default  %+v", o._statusCode, o.Payload)
}

func (o *ExportDhcpPolicySetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ExportDhcpPolicySetBody export dhcp policy set body
swagger:model ExportDhcpPolicySetBody
*/
type ExportDhcpPolicySetBody struct {

	// context
	Context *models.WSContext `json:"context,omitempty"`
}

// Validate validates this export dhcp policy set body
func (o *ExportDhcpPolicySetBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateContext(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ExportDhcpPolicySetBody) validateContext(formats strfmt.Registry) error {

	if swag.IsZero(o.Context) { // not required
		return nil
	}

	if o.Context != nil {
		if err := o.Context.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("wscontext" + "." + "context")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ExportDhcpPolicySetBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ExportDhcpPolicySetBody) UnmarshalBinary(b []byte) error {
	var res ExportDhcpPolicySetBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
