// Code generated by go-swagger; DO NOT EDIT.

package d_h_c_p_policy_set

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// ImportDhcpPolicySetReader is a Reader for the ImportDhcpPolicySet structure.
type ImportDhcpPolicySetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ImportDhcpPolicySetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewImportDhcpPolicySetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewImportDhcpPolicySetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewImportDhcpPolicySetOK creates a ImportDhcpPolicySetOK with default headers values
func NewImportDhcpPolicySetOK() *ImportDhcpPolicySetOK {
	return &ImportDhcpPolicySetOK{}
}

/*ImportDhcpPolicySetOK handles this case with default header values.

Imports of DhcpPolicySet completed
*/
type ImportDhcpPolicySetOK struct {
	Payload *ImportDhcpPolicySetOKBody
}

func (o *ImportDhcpPolicySetOK) Error() string {
	return fmt.Sprintf("[POST /Imports/importDhcpPolicySet][%d] importDhcpPolicySetOK  %+v", 200, o.Payload)
}

func (o *ImportDhcpPolicySetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ImportDhcpPolicySetOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewImportDhcpPolicySetDefault creates a ImportDhcpPolicySetDefault with default headers values
func NewImportDhcpPolicySetDefault(code int) *ImportDhcpPolicySetDefault {
	return &ImportDhcpPolicySetDefault{
		_statusCode: code,
	}
}

/*ImportDhcpPolicySetDefault handles this case with default header values.

Error response
*/
type ImportDhcpPolicySetDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the import dhcp policy set default response
func (o *ImportDhcpPolicySetDefault) Code() int {
	return o._statusCode
}

func (o *ImportDhcpPolicySetDefault) Error() string {
	return fmt.Sprintf("[POST /Imports/importDhcpPolicySet][%d] importDhcpPolicySet default  %+v", o._statusCode, o.Payload)
}

func (o *ImportDhcpPolicySetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ImportDhcpPolicySetBody import dhcp policy set body
swagger:model ImportDhcpPolicySetBody
*/
type ImportDhcpPolicySetBody struct {

	// ws dhcp policy set
	WsDhcpPolicySet *models.WSDhcpPolicySet `json:"wsDhcpPolicySet,omitempty"`
}

// Validate validates this import dhcp policy set body
func (o *ImportDhcpPolicySetBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateWsDhcpPolicySet(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ImportDhcpPolicySetBody) validateWsDhcpPolicySet(formats strfmt.Registry) error {

	if swag.IsZero(o.WsDhcpPolicySet) { // not required
		return nil
	}

	if o.WsDhcpPolicySet != nil {
		if err := o.WsDhcpPolicySet.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Import Parameters" + "." + "wsDhcpPolicySet")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ImportDhcpPolicySetBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ImportDhcpPolicySetBody) UnmarshalBinary(b []byte) error {
	var res ImportDhcpPolicySetBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*ImportDhcpPolicySetOKBody import dhcp policy set o k body
swagger:model ImportDhcpPolicySetOKBody
*/
type ImportDhcpPolicySetOKBody struct {

	// result
	Result string `json:"result,omitempty"`
}

// Validate validates this import dhcp policy set o k body
func (o *ImportDhcpPolicySetOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ImportDhcpPolicySetOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ImportDhcpPolicySetOKBody) UnmarshalBinary(b []byte) error {
	var res ImportDhcpPolicySetOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
