// Code generated by go-swagger; DO NOT EDIT.

package d_h_c_p_server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// EndExportDhcpServerReader is a Reader for the EndExportDhcpServer structure.
type EndExportDhcpServerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EndExportDhcpServerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEndExportDhcpServerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewEndExportDhcpServerDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEndExportDhcpServerOK creates a EndExportDhcpServerOK with default headers values
func NewEndExportDhcpServerOK() *EndExportDhcpServerOK {
	return &EndExportDhcpServerOK{}
}

/*EndExportDhcpServerOK handles this case with default header values.

Exports of DhcpServer completed
*/
type EndExportDhcpServerOK struct {
}

func (o *EndExportDhcpServerOK) Error() string {
	return fmt.Sprintf("[POST /Exports/endExportDhcpServer][%d] endExportDhcpServerOK ", 200)
}

func (o *EndExportDhcpServerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEndExportDhcpServerDefault creates a EndExportDhcpServerDefault with default headers values
func NewEndExportDhcpServerDefault(code int) *EndExportDhcpServerDefault {
	return &EndExportDhcpServerDefault{
		_statusCode: code,
	}
}

/*EndExportDhcpServerDefault handles this case with default header values.

Error response
*/
type EndExportDhcpServerDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the end export dhcp server default response
func (o *EndExportDhcpServerDefault) Code() int {
	return o._statusCode
}

func (o *EndExportDhcpServerDefault) Error() string {
	return fmt.Sprintf("[POST /Exports/endExportDhcpServer][%d] endExportDhcpServer default  %+v", o._statusCode, o.Payload)
}

func (o *EndExportDhcpServerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*EndExportDhcpServerBody end export dhcp server body
swagger:model EndExportDhcpServerBody
*/
type EndExportDhcpServerBody struct {

	// context
	Context *models.WSContext `json:"context,omitempty"`
}

// Validate validates this end export dhcp server body
func (o *EndExportDhcpServerBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateContext(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *EndExportDhcpServerBody) validateContext(formats strfmt.Registry) error {

	if swag.IsZero(o.Context) { // not required
		return nil
	}

	if o.Context != nil {
		if err := o.Context.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Exports Parameters" + "." + "context")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *EndExportDhcpServerBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *EndExportDhcpServerBody) UnmarshalBinary(b []byte) error {
	var res EndExportDhcpServerBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
