// Code generated by go-swagger; DO NOT EDIT.

package d_h_c_p_server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewExportDhcpServerParams creates a new ExportDhcpServerParams object
// with the default values initialized.
func NewExportDhcpServerParams() *ExportDhcpServerParams {
	var ()
	return &ExportDhcpServerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewExportDhcpServerParamsWithTimeout creates a new ExportDhcpServerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewExportDhcpServerParamsWithTimeout(timeout time.Duration) *ExportDhcpServerParams {
	var ()
	return &ExportDhcpServerParams{

		timeout: timeout,
	}
}

// NewExportDhcpServerParamsWithContext creates a new ExportDhcpServerParams object
// with the default values initialized, and the ability to set a context for a request
func NewExportDhcpServerParamsWithContext(ctx context.Context) *ExportDhcpServerParams {
	var ()
	return &ExportDhcpServerParams{

		Context: ctx,
	}
}

// NewExportDhcpServerParamsWithHTTPClient creates a new ExportDhcpServerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewExportDhcpServerParamsWithHTTPClient(client *http.Client) *ExportDhcpServerParams {
	var ()
	return &ExportDhcpServerParams{
		HTTPClient: client,
	}
}

/*ExportDhcpServerParams contains all the parameters to send to the API endpoint
for the export dhcp server operation typically these are written to a http.Request
*/
type ExportDhcpServerParams struct {

	/*Wscontext
	  The results from an initExportDhcpServer operation

	*/
	Wscontext ExportDhcpServerBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the export dhcp server params
func (o *ExportDhcpServerParams) WithTimeout(timeout time.Duration) *ExportDhcpServerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the export dhcp server params
func (o *ExportDhcpServerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the export dhcp server params
func (o *ExportDhcpServerParams) WithContext(ctx context.Context) *ExportDhcpServerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the export dhcp server params
func (o *ExportDhcpServerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the export dhcp server params
func (o *ExportDhcpServerParams) WithHTTPClient(client *http.Client) *ExportDhcpServerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the export dhcp server params
func (o *ExportDhcpServerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWscontext adds the wscontext to the export dhcp server params
func (o *ExportDhcpServerParams) WithWscontext(wscontext ExportDhcpServerBody) *ExportDhcpServerParams {
	o.SetWscontext(wscontext)
	return o
}

// SetWscontext adds the wscontext to the export dhcp server params
func (o *ExportDhcpServerParams) SetWscontext(wscontext ExportDhcpServerBody) {
	o.Wscontext = wscontext
}

// WriteToRequest writes these params to a swagger request
func (o *ExportDhcpServerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Wscontext); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
