// Code generated by go-swagger; DO NOT EDIT.

package d_h_c_p_server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetEffectiveDhcpServersForContainerParams creates a new GetEffectiveDhcpServersForContainerParams object
// with the default values initialized.
func NewGetEffectiveDhcpServersForContainerParams() *GetEffectiveDhcpServersForContainerParams {
	var ()
	return &GetEffectiveDhcpServersForContainerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetEffectiveDhcpServersForContainerParamsWithTimeout creates a new GetEffectiveDhcpServersForContainerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetEffectiveDhcpServersForContainerParamsWithTimeout(timeout time.Duration) *GetEffectiveDhcpServersForContainerParams {
	var ()
	return &GetEffectiveDhcpServersForContainerParams{

		timeout: timeout,
	}
}

// NewGetEffectiveDhcpServersForContainerParamsWithContext creates a new GetEffectiveDhcpServersForContainerParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetEffectiveDhcpServersForContainerParamsWithContext(ctx context.Context) *GetEffectiveDhcpServersForContainerParams {
	var ()
	return &GetEffectiveDhcpServersForContainerParams{

		Context: ctx,
	}
}

// NewGetEffectiveDhcpServersForContainerParamsWithHTTPClient creates a new GetEffectiveDhcpServersForContainerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetEffectiveDhcpServersForContainerParamsWithHTTPClient(client *http.Client) *GetEffectiveDhcpServersForContainerParams {
	var ()
	return &GetEffectiveDhcpServersForContainerParams{
		HTTPClient: client,
	}
}

/*GetEffectiveDhcpServersForContainerParams contains all the parameters to send to the API endpoint
for the get effective dhcp servers for container operation typically these are written to a http.Request
*/
type GetEffectiveDhcpServersForContainerParams struct {

	/*Container
	  Container name for which to return the list effective DHCP servers

	*/
	Container string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get effective dhcp servers for container params
func (o *GetEffectiveDhcpServersForContainerParams) WithTimeout(timeout time.Duration) *GetEffectiveDhcpServersForContainerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get effective dhcp servers for container params
func (o *GetEffectiveDhcpServersForContainerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get effective dhcp servers for container params
func (o *GetEffectiveDhcpServersForContainerParams) WithContext(ctx context.Context) *GetEffectiveDhcpServersForContainerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get effective dhcp servers for container params
func (o *GetEffectiveDhcpServersForContainerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get effective dhcp servers for container params
func (o *GetEffectiveDhcpServersForContainerParams) WithHTTPClient(client *http.Client) *GetEffectiveDhcpServersForContainerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get effective dhcp servers for container params
func (o *GetEffectiveDhcpServersForContainerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContainer adds the container to the get effective dhcp servers for container params
func (o *GetEffectiveDhcpServersForContainerParams) WithContainer(container string) *GetEffectiveDhcpServersForContainerParams {
	o.SetContainer(container)
	return o
}

// SetContainer adds the container to the get effective dhcp servers for container params
func (o *GetEffectiveDhcpServersForContainerParams) SetContainer(container string) {
	o.Container = container
}

// WriteToRequest writes these params to a swagger request
func (o *GetEffectiveDhcpServersForContainerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param container
	qrContainer := o.Container
	qContainer := qrContainer
	if qContainer != "" {
		if err := r.SetQueryParam("container", qContainer); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
