// Code generated by go-swagger; DO NOT EDIT.

package d_h_c_p_server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/CMSgov/CMS-AWS-West-Network-Architecture/vpc-automation/swagger/models"
)

// InitExportDhcpServerReader is a Reader for the InitExportDhcpServer structure.
type InitExportDhcpServerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InitExportDhcpServerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewInitExportDhcpServerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewInitExportDhcpServerDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewInitExportDhcpServerOK creates a InitExportDhcpServerOK with default headers values
func NewInitExportDhcpServerOK() *InitExportDhcpServerOK {
	return &InitExportDhcpServerOK{}
}

/*InitExportDhcpServerOK handles this case with default header values.

Exports of DhcpServer initialized
*/
type InitExportDhcpServerOK struct {
	Payload *models.WSContext
}

func (o *InitExportDhcpServerOK) Error() string {
	return fmt.Sprintf("[POST /Exports/initExportDhcpServer][%d] initExportDhcpServerOK  %+v", 200, o.Payload)
}

func (o *InitExportDhcpServerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WSContext)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewInitExportDhcpServerDefault creates a InitExportDhcpServerDefault with default headers values
func NewInitExportDhcpServerDefault(code int) *InitExportDhcpServerDefault {
	return &InitExportDhcpServerDefault{
		_statusCode: code,
	}
}

/*InitExportDhcpServerDefault handles this case with default header values.

Error response
*/
type InitExportDhcpServerDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the init export dhcp server default response
func (o *InitExportDhcpServerDefault) Code() int {
	return o._statusCode
}

func (o *InitExportDhcpServerDefault) Error() string {
	return fmt.Sprintf("[POST /Exports/initExportDhcpServer][%d] initExportDhcpServer default  %+v", o._statusCode, o.Payload)
}

func (o *InitExportDhcpServerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*InitExportDhcpServerBody init export dhcp server body
swagger:model InitExportDhcpServerBody
*/
type InitExportDhcpServerBody struct {

	// filter
	Filter string `json:"filter,omitempty"`

	// first result pos
	FirstResultPos int64 `json:"firstResultPos,omitempty"`

	// options
	Options []string `json:"options"`

	// page size
	PageSize int64 `json:"pageSize,omitempty"`
}

// Validate validates this init export dhcp server body
func (o *InitExportDhcpServerBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *InitExportDhcpServerBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *InitExportDhcpServerBody) UnmarshalBinary(b []byte) error {
	var res InitExportDhcpServerBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
